### PR TITLE
Customer Segmentation using ML

### PR DESCRIPTION
**Pull request by theanshulcode**

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Hey, have you pushed the code? @theanshulcode

**Comment by theanshulcode** [comment]
Yes .

**Comment by prathimacode-hub** [comment]
Can you resolve the merge conflicts from your end. You had made changes in project README due to which conflicts arised. Else, create a new PR with your project files. @theanshulcode

**Comment by prathimacode-hub** [comment]
What are you doing, I really don't get you. I don't find any source code except the changes you made in project readme file. I also said, you said never close issues or pull request from your end. if you have any queries, do ask. @theanshulcode

**Comment by prathimacode-hub** [comment]
Why had you closed the issue? @theanshulcode

**Comment by prathimacode-hub** [comment]
?? @theanshulcode

**Pull request closed without merging**
