### PR TITLE
House Price Prediction model

### PR DESCRIPTION
**Pull request by harshita9621**
# About the data:

The real estate markets, like those in Sydney and Melbourne, present an interesting opportunity for data analysts to analyze and predict where property prices are moving towards. Prediction of property prices is becoming increasingly important and beneficial. Property prices are a good indicator of both the overall market condition and the economic health of a country.

Fixes: #27
## Columns

- **Date**: Date when the house is ready for sale.
- **Price**: Price of the house to be sold.
- **Bedrooms**: No. of bedrooms in the house.
- **Bathrooms**: No. of bathrooms in the house.
- **Sqft_living**: Squarefoot of Living in the house.
-**Sqft_lot**: Squarefoot of Floor in the house.
- **Floors**: Floors on which living area located.
- **Waterfront**: If waterfront available in front of house.
- **View**: Vie from the house.
- **Condition**: Condition of the house.
- **Sqft_above**: Squarefoot above is the space available at roof.

**MODELS USED**
-  Linear Regression
-  K-Nearest Neighbors
-  Random Forest Regressor
-  Decision Tree Regressor

**LIBRARIES NEEDED**
- numpy
- pandas
- seaborn
- matplotlib
- scikit-learn
- One hot encoding

### CODE REVIEW

**Comment by harshita9621** [comment]
@prathimacode-hub I make the changes in readme file , Please review this PR.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your .ipynb file is empty
The readme files of the project's filename should be as "README.md"

**Comment by prathimacode-hub** [comment]
Your project file .ipynb is empty. @harshita9621

**Comment by harshita9621** [comment]
@prathimacode-hub please give me time I will change

**Comment by prathimacode-hub** [comment]
Ok, notify once you are done. @harshita9621

**Comment by harshita9621** [comment]
sure

**Comment by harshita9621** [comment]
@prathimacode-hub I correct the mistake please check the file.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged successfully. You can take up an another issue to work on. Congrats.🎇@harshita9621

**Comment by harshita9621** [comment]
@prathimacode-hub Thanks

**Pull request merged**
