### PR TITLE
Age gender ethnicity

### PR DESCRIPTION
**Pull request by Anshal55**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #138 

### Describe the add-ons or changes you've made

I have added models to predict age,gender and ethnicity of a person.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have tested all the models multiple times and deployed model on several images.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Manasi2001** [comment]
Looks perfect to me @Anshal55. Very well done!!
I'm going to let the PA take a look at this as well, then I'll merge it. ✌🏻

**Comment by Anshal55** [comment]
> Looks perfect to me @Anshal55. Very well done!!
> I'm going to let the PA take a look at this as well, then I'll merge it. ✌🏻

Thanks a lot!!

**Comment by prathimacode-hub** [comment]
Amazing work shown. Your PR was a pin point to the issue. Crystal clear. Keep shining. Whooaa. 👌👌👌@Anshal55

**Comment by Anshal55** [comment]
> Amazing work shown. Your PR was a pin point to the issue. Crystal clear. Keep shining. Whooaa. ok_handok_handok_hand@Anshal55

Thanks a lot!! 
It means a lot!!

**Pull request merged**
