### PR TITLE
Breast Cancer Prediction

### LINKED ISSUE #80: Breast Cancer Prediction
Hey LGM-SoC participants, good to see you.

This project helps in predicting whether the patient who is suffering from breast cancer is benign or malignant.

Dataset : https://www.kaggle.com/uciml/breast-cancer-wisconsin-data

If you like to work on this issue, follow the given guidelines for code as well as for the README.

Enjoy your open source journey!😎

### PR DESCRIPTION
**Pull request by Jagannath8**
**Breast Cancer Prediction**

**Objective**
The main objective of this project is to use Logistic Regression algorithm to predict breast cancer.

**Describe the add-ons or changes you've made**
Added folders for dataset and model for 'Breast Cancer Prediction'.

**How Has This Been Tested?**
Manually tested.

Fixes #80

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
If you want, you can add up more algorithms to this project to compare the accuracy. @

The PR you created has only issue number, it doesn't have any template. Kindly follow that. 

@Jagannath8

**Comment by Jagannath8** [comment]
@prathimacode-hub mam, I've made the changes.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged successfully. 👌✔@Jagannath8

**Comment by Jagannath8** [comment]
Can I start working on issue #86

**Pull request merged**
