### PR TITLE
Guess Which Flower - Iris Dataset

### PR DESCRIPTION
**Pull request by Sidhved**
- [x] Added Dataset 
- [x] Added Source Notebook
- [x] Linked every resource in Readme.md
- [x] Finished Model Creation Process

### CODE REVIEW

**Comment by Sidhved** [comment]
@prathimacode-hub can we go forward and merge this pr?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The PR commit message should have a PR template
Change the project title name to "Iris Flower Classification"
All images and screenshots should be added up in "Images" folder.
And README.md and iris_flower_classification.ipynb should be in "Model" folder

Kindly do the needful changes. @Sidhved

**Comment by Sidhved** [comment]
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #77

### Describe the add-ons or changes you've made

Model Creation for Classification of type of Flower using the IRIS Dataset

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The accuracy of the model has been compared using Cross-Validation Score

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

**Review by prathimacode-hub — APPROVED** [review]
PR is approved. Well done. ✨🏷@Sidhved

**Pull request merged**
