### PR TITLE
Market Basket Analysis

### PR DESCRIPTION
**Pull request by jeffryjames**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

Closes: #436 

### Describe the add-ons or changes you've made

Created a Model for Market Basket Analysis

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Deployed Using Flask

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add up the issue number to your PR template. @jeffryjames

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure given and do the changes accordingly. @jeffryjames

**Comment by jeffryjames** [comment]
> Kindly follow the project structure given and do the changes accordingly. @jeffryjames

Where can I find that, Should I Change the format of uploading or the project?

**Comment by prathimacode-hub** [comment]
> > Kindly follow the project structure given and do the changes accordingly. @jeffryjames
> 
> Where can I find that, Should I Change the format of uploading or the project?

It's found in the README file of this project. @jeffryjames

**Comment by prathimacode-hub** [comment]
Project structure is not right. Change it. Once you correct it with right structure, I shall check on to PR. Kindly do the addressed changes. @jeffryjames

**Comment by prathimacode-hub** [comment]
Its been 9days and no update yet form you. @jeffryjames

**Comment by prathimacode-hub** [comment]
9th is the last date to accept PR's. If you wouldn't do it by then, obviously you can submit later but points won't be counted towards DCP program. @jeffryjames

**Comment by prathimacode-hub** [comment]
It's been 13 days. No respnse yet. Unfortunately time is up for DCP program so I have to remove the DCP label. Still you work on it and correct keeping in mind that it should be completed in 3 days. For any PR max time is 5days. I had given enough time beyond that. @jeffryjames

**Pull request closed without merging**
