### PR TITLE
Updated The "Look Through the Kart of Amazing Projects" in README

### PR DESCRIPTION
**Pull request by khushi-purwar**
## Related Issue  #402 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #402  that will be closed through this PR

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by khushi-purwar** [comment]
@prathimacode-hub  I have added all the projects in the README.md file. Please check, let me know, if any changes require.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Hey, thanks for your efforts into this repo. Just gone through it. 3 projects are missing from the list. 

1. Fake Job Posting Prediction
2. Dry Beans Classification
3. Shoulder XRay Classification

Do you want to add this on or shall I? It's upto you. @khushi-purwar

**Comment by khushi-purwar** [comment]
> Hey, thanks for your efforts into this repo. Just gone through it. 3 projects are missing from the list.
> 
> 1. Fake Job Posting Prediction
> 2. Dry Beans Classification
> 3. Shoulder XRay Classification
> 
> Do you want to add this on or shall I? It's upto you. @khushi-purwar

I will do it.

**Comment by khushi-purwar** [comment]
Done! @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
Looks perfect. PR is approved. Welcome to repo officially. Congrats on your first PR. Yayy. 🤩👍@khushi-purwar

**Comment by khushi-purwar** [comment]
> Looks perfect. PR is approved. Welcome to repo officially. Congrats on your first PR. Yayy. 🤩👍@khushi-purwar

Thanks @prathimacode-hub 

> Looks perfect. PR is approved. Welcome to repo officially. Congrats on your first PR. Yayy. 🤩👍@khushi-purwar

Thanks 😊 @prathimacode-hub

**Comment by prathimacode-hub** [comment]
You're already in, so you can choose up an issue from grabs or raise an issue interested to work on. @khushi-purwar 👍

**Comment by khushi-purwar** [comment]
> You're already in, so you can choose up an issue from grabs or raise an issue interested to work on. @khushi-purwar 👍

Ok.

**Pull request merged**
