### PR TITLE
IMDB Sentiment analysis

### PR DESCRIPTION
**Pull request by shivani6320**
## IMDB Sentiment Analysis

- The purpose of this project is to analyze IMDB Movies reviews and predict sentiments behind them.

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

Closes: #466 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
In project file, you can use multiple algorithms instead on only 1. That way you can optimize it and compare the efficiency across models.
Create "requirements.txt" file with all the libraries you had used in this project
Also dataset folder should be as "Dataset". Since you couldn't load up the .csv files duee to larger size, instead in README.md along with the link provided, list out the attributes used in the Dataset.
You can also add data visualizations in "Images" folder and add up those links in README.md 
Your README.md needs more elaboration. 

Kindly do the needful changes. @shivani6320

**Comment by shivani6320** [comment]
@prathimacode-hub , I have made the requested changes, please check.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Yayy, great going. 🤩👌@shivani6320

**Comment by prathimacode-hub** [comment]
Only DCP program has PR form to fill once its merged not LGMSoC. So for this PR, you can fill out the form provided in prpject channel. @shivani6320

**Comment by prathimacode-hub** [comment]
You haven't filled up the PR link from for this particular PR. And also make sure you add the right PR link to the form. Kindly do it. @shivani6320

**Pull request merged**
