### PR TITLE
Body Fat Prediction

### PR DESCRIPTION
**Pull request by Jagannath8**
## Body Fat Prediction

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

##Objective
The main objective of this project is to use Machine Learning algorithms to predict percentage of body fat.

##Describe the add-ons or changes you've made
Added folders for Dataset, Model and Images for 'Body Fat Prediction'.

##How Has This Been Tested?
Manually tested.

Closes: #316

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
As usual, fab work showcased. I could see you had imported the model into pickle. So do add that file as well in "Model" folder. @Jagannath8

**Comment by Jagannath8** [comment]
I've added the pkl file

**Review by prathimacode-hub — APPROVED** [review]
I appreciate the work you put up. Good going. ✨🙌@Jagannath8

**Comment by Jagannath8** [comment]
Thankuu @prathimacode-hub mam

**Pull request merged**
