### PR TITLE
Added Object Detection using OpenCV

### PR DESCRIPTION
**Pull request by vaishnavipatil4848**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

Closes: #484 

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made
* Made object detection model using OpenCV using the coco dataset. This helps to detect objects in live video stream and draw bounding box around them.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made
* I have personally verified the code using live object detection on my PC.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by vaishnavipatil4848** [comment]
Hello
This pull request needs to be merged.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Add "requirements.txt" file with all the libraries used in this project
And the project file should be in .ipynb and not .py file. Also the code should have appropriate comments to get good understanding of the project.

Kindly address these changes. @vaishnavipatil4848

**Comment by vaishnavipatil4848** [comment]
I have done the requested changes as per listed. Comments have been added wherever required.

**Review by prathimacode-hub — APPROVED** [review]
PR is approved. Yayy. Congrats on your first PR and welcome to the repo officially. It was a great start. ✨🎉👏@vaishnavipatil4848

**Pull request merged**
