### PR TITLE
NBA-Analysis AND Prediction

### PR DESCRIPTION
**Pull request by aryantiwari10**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

Closes: #413

### Describe the add-ons or changes you've made

 In this project first I performed a exploratory data analysis on the NBA dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model prediction part I used total 9 machine learning algos . In each algo I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset .

MODELS USED : I used total 11 machine leaning algos in the dataset
Logistic Regression
KNeighborsClassifier
SVC
Naive Bayes
DECISION TREE CLASSIFIER
RandomForestClassifier
AdaBoostClassifier
Gradient Boosting Classifier
XGBClassifier
ExtraTreesClassifier
Bagging Classifier

LIBRARIES:
PANDAS
NUMPY
MATPLOTLIB
SEABORN
SCIPY
SKLEARN

CONCLUSION : We get to know that most number of points were scored in the season 2013-2014 by the NBA players.

We get a training score of 100 % using the Random Forest Classifier and Extra Trees Classifier which is quite good.
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

Follow the project structure. Give proper file names to it.

- The project folder should be titled as "NBA - Analysis and Prediction"
- The .zip file you added up at "Dataset", give it as "dataset.zip".
- The readme file shuld be as README.md
- The project file should be titled as "nba_analysis_and_prediction.ipynb"
- In 'README.md' file, add short description about what the project is. Add accuracies you had secured for all the algorithms you had applied to the project, compare the accuracies, conclude it and your name at the end of the file.

For reference, you can check up with this [repo](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Kidney%20Stone%20Prediction) of how project should look like.

Kindly do these needful changes. @aryantiwari10

**Comment by prathimacode-hub** [comment]
I couldn't see the right changes I had asked for eyet. Do check it out. Look step by step about changes you got to do. You can do this. @aryantiwari10

**Comment by aryantiwari10** [comment]
Mam please have a look how is it correct now?

**Review by prathimacode-hub — APPROVED** [review]
Spot on. Amazing justification to the project taken up. Kudos to you for your perfection. Keep it up. 🤩🎇🙌@aryantiwari10

**Comment by aryantiwari10** [comment]
Thank you so much!!

**Pull request merged**
