### PR TITLE
ISSUE Template problem solved

### LINKED ISSUE #55: Issue template not working
I saw the repo and found that there is an issue template but it's not working when I am here to create an issue so I want to solve this problem. 
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Subhangini**
fixes #55

### CODE REVIEW

**Comment by Subhangini** [comment]
@prathimacode-hub Please review this PR

**Comment by prathimacode-hub** [comment]
Kindly add the PR template to get this issue counted under LGMSOC. @Subhangini

**Comment by Subhangini** [comment]
> Kindly add the PR template to get this issue counted under LGMSOC. @Subhangini

ok

**Comment by prathimacode-hub** [comment]
I asked to use the pull request template available for your PR commit message. Not to change the pull request template that's in .github @Subhangini

**Comment by Subhangini** [comment]
Ok, I misunderstood that, but i think your PR template was also nit working
so should i leave those changes or change them back

**Review by prathimacode-hub — APPROVED** [review]
Nope, glad you did that as well. That's fine. Let it be.  Thanks for notifying and for initiating to solve this. I appreciate your efforts. Well done. 👏🏷

**Pull request merged**
