### PR TITLE
Car insurance prediction

### PR DESCRIPTION
**Pull request by soma2000-lang**
## 463
- [x] LGM-SOC'21 Participant 

Closes: #463

### Describe the add-ons or changes you've made

In this model I have tried o predict the car insurance using Random Forest Regressorand some preprocessing techniques
Model added -Car insurance prediction

-
- [x]New feature (non-breaking change which adds functionality)

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@prathimacode-hub 
Please have a look

**Comment by soma2000-lang** [comment]
@prathimacode-hub Should I cahnge the issue no to #483

**Comment by soma2000-lang** [comment]
@prathimacode-hub comment for any changes

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub Should I change the issue no to #483

Not needed, issue number is correct, but your PR template needs few details about the project. @soma2000-lang

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your project is not in right format neither file names are appropriate. Kindly check the README file of the project. It has the project structure included.

Kindly do the changes. 👍@soma2000-lang

**Comment by soma2000-lang** [comment]
@prathimacode-hub  made the changes kindly merge

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The project folder should be as "Car Insurance Prediction.
The model folder shoudl be as "Model".
The goal you had written in README.md is incomplete.
Be elaborative with your README.md file, add all the models along with accuracies achieved for each model you had used in Accuracies section.
Also write descriptive conclusion derived from this project.
In Dataset section of README.md, add the link of the dataset.
Even in Dataset folder, add README.md file and include dataset link along with the attributesof datasets used in this project.
In .ipynb file, you can do analysis using data visualizations. This is where project comes up as a playground. 

Kindly do these changes. @soma2000-lang

**Comment by soma2000-lang** [comment]
@prathimacode-hub  I had used only one model so the accuracy of only one model is given
The rest of the changes I will be doing by tonight

**Comment by soma2000-lang** [comment]
@prathimacode-hub  made all the changes kindly check

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The model folder should be titled as "Model"
The link of datasets you added in both README.md are not opening up. Kindly correct the links.
Elaborate the accuracy section and list out the models used there with their appropriate accuracy scores you had secured.
The project file should be as "car_insurance"prediction.ipynb"
Add "requirements.txt" as well with all the libarries used in this project according to the project structure given in README file of this project. 
Also include the data visualizations you had done in your project file in "Images" folder and add those image links in README.md file of your project.

Kindly do these changes. @soma2000-lang

**Comment by soma2000-lang** [comment]
@prathimacode-hub  the model folder is named as Model only also since I have used only one mode hence accuracy of only one model has been given in the README.

The rest of the changes I am doing

**Comment by soma2000-lang** [comment]
@prathimacode-hub  I dont know how this pr got closed .What to do now please help

**Pull request closed without merging**
