### PR TITLE
Mobile Range Price Classification

### PR DESCRIPTION
**Pull request by Isha307**
## Related Issue 

- Mobile Range Price Classification

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: [#34 ](https://github.com/prathimacode-hub/ML-ProjectKart/issues/34)

### Describe the add-ons or changes you've made

Created Model to predict Mobile Price Range

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Locally

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The project file name should be titled as "mobile_price_range_classification.ipynb"
Images and screenshots should be in "Images" folder

Kindly do this change. @Isha307

**Review by prathimacode-hub — APPROVED** [review]
Kindly do the needful changes to get merged. @Isha307

**Comment by Isha307** [comment]
> Kindly do the needful changes to get merged. @Isha307

okay

**Review by prathimacode-hub — APPROVED** [review]
Yayy. Welcome to the repo. Your PR is approved and merged. That was a awesome work from you. 🎇👌👏 @Isha307

**Comment by Isha307** [comment]
> Yayy. Welcome to the repo. Your PR is approved and merged. That was a awesome work from you. 🎇👌👏 @Isha307

Thank you 🤞👍✨

**Pull request merged**
