### PR TITLE
Forest Cover Type Classification

### PR DESCRIPTION
**Pull request by rammya29**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #189 

### Describe the add-ons or changes you've made
 I have created a model where it classifies based on the cover type of the forest such as it takes features like soil type, elevation, slope, etc.    

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
    The model is tested in the google colab workspace, just download run it either in jupyter notebook or colab space.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Manasi2001** [comment]
Hey @rammya29, your analysis is very good but the prediction has been performed on a very imbalanced dataset.
image
Try to use cross validation and then make the predictions. This will increase your precision and recall as well.

**Comment by rammya29** [comment]
I will try to change it

**Review by prathimacode-hub — COMMENTED** [review]
Here you had used Random Forest, have you tried up with other algorithms? @rammya29

**Comment by rammya29** [comment]
Yes, first I tried with random Forest Classifier then I done with Logistic Regression. Should I redo this with some other alogorithm

**Comment by prathimacode-hub** [comment]
> Yes, first I tried with random Forest Classifier then I done with Logistic Regression. Should I redo this with some other alogorithm

Yes, it's better if you try with multiple algorithms, that way you would increase the optimization and could as well compare the accuracies to see how model is performing. @rammya29

**Comment by Manasi2001** [comment]
Good job @rammya29!! Nicely done now. ✨✨

**Pull request merged**
