### PR TITLE
Spam Email Detection

### PR DESCRIPTION
**Pull request by sai-keerthi**
## Related Issue : 

- The aim of the project is to analyze the message and classify weather its a spam or ham. The model created classifies the message as spam or ham

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #24 

### Describe the add-ons or changes you've made

- Data exploration
- Model creation( Logistic Regression, Naive Bayes)

## Type of change

What sort of change have you made:

- [x] My code follows the code style of this project.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

.ipynb file and README.md file should be in "Model" folder
.csv file should be in "Dataset" folder
The project folder should be titled as "Spam Email Detection"
The file name of the project should be as "spam_email_detection.ipynb
What's this Spam Message Detector? Is it folder or file? Kindly remove that.
Add accuracies of both Naive Bayes and Logistic Regression in your README and show up the conclusion. 

You had shown good improvement. Kindly do the needful changes. @sai-keerthi

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The folder should be titled as "Model" not "Module". Kindly do this change. @sai-keerthi

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and will be merged soon. Congratulations. This was a good kick start. Your efforts are appreciated. 👌🎉✨@sai-keerthi

**Comment by sai-keerthi** [comment]
@prathimacode-hub  Thank you mam

**Pull request merged**
