### PR TITLE
Fake News Detection

### PR DESCRIPTION
**Pull request by Soumayan-pal01**
## Fake News Detection

- The aim of the project is to detect whether the news is Real or Fake using different text extraction NLP techniques to understand the data, use different classifiers approaches and RNN framework on this training data to train various models and use them to make detections. 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #17

### Describe the add-ons or changes you've made

- Trained different classifier models using count and Tf-IDF vectorizers.
- Trained a RNN model to make detections.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — APPROVED** [review]
As usual, your PR's are always the finest ones. Nothing to be pointed out. Crystal clear. Your work is far beyond. Exceptional. Good to know you as a participant through LGMSOC. Strong Applause for you. 🎉🎇🙌 @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
Thank you @prathimacode-hub . I would like to raise an issue for Solar Eclipse Classification project. Can I proceed with it ?

**Comment by prathimacode-hub** [comment]
Yeah, sure you can. Feel free to raise your issue. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
Okhay

**Pull request merged**
