### PR TITLE
Medical Cost Analysis for Smokers and Non-smokers #114

### PR DESCRIPTION
**Pull request by abhisheks008**
## Issue #114 Medical Cost Analysis for Smokers and Non-smokers

- This project will contain the back end development and model creation for predicting the average medical cost of the smokers as compared to the non-smokers. Apart from that, it will do an EDA which will provide the analysis of the data based on various features like, gender, age. region and many more things. In this project it will also show the visual analysis using the joint and the scatter plots.

- [x] LGM-SOC'21 Participant 

Closes: #114 

### Describe the add-ons or changes you've made
This project consists of two parts,
1. Exploratory Data Analysis of the dataset based on various features.
2. Finding out the best algorithm which will used to make the Prediction model of the average medical cost for the smokers and non-smokers

## Type of change

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
For running the project, first of all we have download the dataset and the ipynb file which consists the codebase, After that open Anaconda Navigator in your system and upload the dataset as well as the main file. 
Required Python libraries : Numpy, Seaborn, Pandas, Matplotlib, os.
For the prediction model, various algorithms are used, (evaluation metrics : CV score)
|Algorithms used | CV Score |
| :---: | :---: |
| Random forest regression | 0.858778 |

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure given in README.md file of this repo. @abhisheks008

**Comment by abhisheks008** [comment]
@prathimacode-hub I have updated the model and the dataset folder as given in the readme file. Now please check it.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Small change. All readme files should be named as "README.md"

@abhisheks008

**Comment by abhisheks008** [comment]
@prathimacode-hub Updated and renamed all the readme.md files into README.md. Can please check it now?

**Review by prathimacode-hub — APPROVED** [review]
Clean and perfect. No changes to be done. Good representation and analysis very well showcased. I highly appreciate your efforts. Kudos to you. Fab work. Congrats. Welome to the repo. Your PR is approved. 👏✨🎉@abhisheks008

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub Updated and renamed all the readme.md files into README.md. Can please check it now?

You had done model creation right, not backend? @abhisheks008

**Comment by abhisheks008** [comment]
@prathimacode-hub yeah I have done the model creation

**Pull request merged**
