### PR TITLE
Mall Customer Segmentation

### PR DESCRIPTION
**Pull request by Rutikab12**
## Related Issue : #349 

- This model segments the mall customers based on certain parameters.

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes : #349 

### WHAT I HAD DONE: 

- Firstly I explored the data in different aspects.
- Then with the help of visualization libraries such as matplotlib and seaborn identified the group of customers.
- With help of that I visualized their pattern of spending.
- Based on this info , applied algorithms.
- And obtained the optimal number of clusters.

### MODELS USED: 

I have used the following model:

- KMeans
- Birch
- AffinityPropagation
- SpectralClustering

Out of these four models, the best result was displayed by KMeans and Birch.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the README.md template given in README file of this project. It should be elaborative enough to describe the project not one line answers. And also you can use multiple algorithms to give good efficiency and provide comparitive results. @Rutikab12

**Comment by Rutikab12** [comment]
Okay @prathimacode-hub

**Comment by Rutikab12** [comment]
> Follow the README.md template given in README file of this project. It should be elaborative enough to describe the project not one line answers. And also you can use multiple algorithms to give good efficiency and provide comparitive results. @Rutikab12

Hey @prathimacode-hub I have done the required changes. Please have a look there. Thanks.

**Comment by Manasi2001** [comment]
Amazing work @Rutikab12!! Your notebook is very impressive. Good job! 🎉

**Comment by Rutikab12** [comment]
> Amazing work @Rutikab12!! Your notebook is very impressive. Good job! 🎉

Thank You @Manasi2001 . Feels Great.

**Pull request merged**
