### PR TITLE
Adding Loan Eligibility Prediction #42

### PR DESCRIPTION
**Pull request by Rutikab12**
**GOAL:**

Loan Eligibility Prediction 
*issue no :* #42 

This model will predict the eligibility of a customer for getting a loan from the company.

**MODELS USED:**
I have used the Logistic Regression algorithm for model building. 

**WHAT I HAD DONE:**
I have done the following operations on the given dataset.
- Data Exploration
- Data Cleaning
- Data Visualization
- Model Building
- Prediction.

**LIBRARIES NEEDED:**
- Pandas 
- Matplotlib
- Seaborn
- Numpy
- Sklearn

**Accuracy:**
- Logistic Regression     0.8216216216216217
- Decision Tree      0.7189189189189189

**CONCLUSION:**
Hence the model built successfully and is ready to predict the eligibility of a customer to get a loan from the company.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

- You had loaded .csv files in "Data". The files should be in "Dataset" folder.
- .ipynb file name should be snake case. That is "loan_eligibility_prediction.ipynb"
- The file name of readme file of the project should be README.md
- There is a template for both PR and README available in README file of the project.

Kindly follow it and do the needed changes. @Rutikab12

**Comment by Rutikab12** [comment]
> Changes to be done 👍
> 
> * You had loaded .csv files in "Data". The files should be in "Dataset" folder.
> * .ipynb file name should be snake case. That is "loan_eligibility_prediction.ipynb"
> * The file name of readme file of the project should be README.md
> * There is a template for both PR and README available in README file of the project.
> * You had used only 1 algorithm, Use 2 to 3 algorithms and compare the accuracy to know the efficiency.
> 
> Kindly follow it and do the needed changes. @Rutikab12

Done with changes. Please Review. Thank You! @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
- The file name of readme file of the project should be README.md
- Add the issue number you had provided solution to in your PR comment.
- You had used only 1 algorithm, Use 2 to 3 algorithms and compare the accuracy to know the efficiency.
- Also add up the accuracies you had got for those algorithms in README file of your project.

Do these changes @Rutikab12

**Comment by prathimacode-hub** [comment]
You shouldn't close your PR from your end. You don't want your PR to get merged? @Rutikab12

**Comment by Rutikab12** [comment]
mistakenly did that.

**Comment by Rutikab12** [comment]
> * The file name of readme file of the project should be README.md
> * Add the issue number you had provided solution to in your PR comment.
> * You had used only 1 algorithm, Use 2 to 3 algorithms and compare the accuracy to know the efficiency.
> * Also add up the accuracies you had got for those algorithms in README file of your project.
> 
> Do these changes @Rutikab12

Done with the changes. @prathimacode-hub. Excuse me for mistakenly closing the PR . Now all the issues are resolved.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged successfully. You can take up an another issue to work on. Congrats. You had done a good work. Great going. ✨👌@Rutikab12

**Pull request merged**
