### PR TITLE
Crop Recommendation System

### PR DESCRIPTION
**Pull request by abhisheks008**
## Related Issue #182 
The Goal of this project is to build the recommendation model using the crop recommendation dataset.

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #182 
### Description
The Goal of this project is to build the recommendation model using the crop recommendation dataset. For that I have used various classification algorithms to train the model.

## Type of change

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
The models are being tested by the accuracy scores.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Manasi2001** [comment]
There's a blank README file in Images folder @abhisheks008. Kindly remove it. Rest is fab. 😎

**Comment by abhisheks008** [comment]
Sorry my bad! :(

**Comment by Manasi2001** [comment]
Now it's good to go. Awesome 🤩🎊

**Review by prathimacode-hub — COMMENTED** [review]
Your work speaks all and you had set your bar very high. And you reach the expectations every single time. Omg, by the time I'm back you're up with 3 PR's. That's phenomenal. 🔥🧨 @abhisheks008

**Pull request merged**
