### PR TITLE
Titanic Survival Prediction

### PR DESCRIPTION
**Pull request by RHEA211**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #23 

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Good Work. But add a proper README.md file. It lacks information. You can follow the README template given in README file of the project. Else you can check up with the other projects README's to know how it should be. @RHEA211

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Provide the accuracies you have got in the model and compare the accuracies in your README.md file. You had used 4 algorithms in your project.
Screenshots and images should be present in "Images" folder and then add the file path to your 'README.md' file. It shouldn't be in 'user-images' content.

Kindly do these changes. @RHEA211

**Comment by RHEA211** [comment]
@prathimacode-hub Ma'am is it fine now?

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Amazing work @RHEA211. You had nailed it. Perfect and clean. Well done. 🎇👌🎉

**Comment by RHEA211** [comment]
Thank you Ma'am

**Comment by prathimacode-hub** [comment]
> Thank you Ma'am

Most welcome. 😎@RHEA211

**Pull request merged**
