### PR TITLE
Star Radiation

### PR DESCRIPTION
**Pull request by rajnish-488**
## Related Issue 
Stars Radiation - Analysis and Prediction
- Info about the related issue : stars Radiation reduction model

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

Closes: #280 

### Describe the add-ons or changes you've made
I had analysis the data and created the models to predict the radiation of the star.
Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [x] Created the model.
- [x] My code follows the code style of this project.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Model is tested using Mean Absolute Error.

## Checklist:
Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure given. @rajnish-488

**Comment by rajnish-488** [comment]
ok, sorry for that

**Comment by rajnish-488** [comment]
Ma'am the changes had been done please review my code .

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The images and screenshots should be in "Images" folder
The .cvs files should be in "Dataset" folder
The project title is "Star Radiation - Analysis and Prediction".. Be clear of wht your project is.
Also project file names should be in snake case, this is the format given : file_name.ipynb
Since you have 2 .ipynb files, the project file for data extraction should be "star_radiation_dataextraction.ipynb
The project file for model creation file should be "star_radiation_model.ipynb
Add "requirements.txt" file to this project which should include and list out all the libraries imported in this project.
Give the proper project title for your PR. Also a spelling mistake. PR title should be as "Star Radiation"

I am adjusting the PR template, so you don't have to do that. All the changes needed are mentioned above. Kindly do the needful changes. @rajnish-488

**Comment by rajnish-488** [comment]
Ma'am I had done all the change give above . Sorry for all the problem I caused you. If there is any more problem please help me to sort it out . And please review my work again

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
 You have renamed the README file to requirements.txt file which doesn't ave any meaning
The "requirements.txt" file should have all the libraries imported in this project
The "README.md" file you added above has no information about the project. Kindly follow this [template](https://github.com/prathimacode-hub/ML-ProjectKart/blob/main/Phishing%20Website%20Detection/Model/README.md), but add it according to your project and work you had done. 

Look through this project, I had shown above. This is how a project structure should look like.

Kindly do these changes. @rajnish-488

**Comment by prathimacode-hub** [comment]
> Ma'am I had done all the change give above . Sorry for all the problem I caused you. If there is any more problem please help me to sort it out . And please review my work again

Sure, don't feel sorry about it. It's ur first time and I understand. Instead of struggling on own, you can ask for help. Never hesitate to ask. You can do this. 👍@rajnish-488

**Comment by rajnish-488** [comment]
Ma'am done .

**Comment by rajnish-488** [comment]
Is the format of my README.md is correct

**Review by prathimacode-hub — APPROVED** [review]
Picture Perfect, amazing work. Congrats. Your first PR is approved. Welcome to the repo officially.  I appreciate your efforts. ✨👌👏@rajnish-488

**Comment by prathimacode-hub** [comment]
> Is the format of my README.md is correct

Absolutely correct. @rajnish-488

**Pull request merged**
