### PR TITLE
Driver_Drowsiness_Detection

### PR DESCRIPTION
**Pull request by jayant766**
I updated the Driver Drowsiness Detection System. Please review it.
also let me know if you want future improvement in this project.

### CODE REVIEW

**Comment by Manasi2001** [comment]
The program looks nice to me @jayant766, but some changes are required.
1. Rename the folder as Driver Drowsiness Detection and not Driver_Drowsiness_Detection.
2. Create a proper README according to [this](https://github.com/prathimacode-hub/ML-ProjectKart/blob/main/.github/readme_template.md) template.

Rest is good to go. Nice job!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Along with the changes @Manasi2001 had provided. There are some additional changes as well.

- It's a computer vision project and that's driver drowsiness. Kindly add project screenshots and video file to justify the project in "Media" folder
- Add these screenshots and video links of it in "README.md" file. Follow the right README.md template. It should be elaborative and descriptive enough.
- Add the imported llibraries in "requirements.txt" file
- The project file and "README.md" should be in "Model" folder.
- Add the PR template to your commit message along with your issue number according to your project.
- The project folder should be titled as "Driver Drowsiness Detection"
- The project file should be titled as "drowsiness_detector.ipynb"

Kindly do the needful changes. @jayant766

**Comment by jayant766** [comment]
#166 I updated all the requirements but I didn't able to rename the project name because I got error while doing it. 
Please review it.

**Comment by Manasi2001** [comment]
Some changes are still requires @jayant766:
1. Readme still needs to be updated.
2. Add the imported libraries in "requirements.txt" file.
3. Your ipynb file is showing an error at the bottom which it definitely should not if you have written the program yourself and ran it at least once. (This requires some explanation from your side @jayant766).

**Comment by Manasi2001** [comment]
And, my doubt was right. This code isn't written by you @jayant766. It's plagiarized @prathimacode-hub.
Source: https://github.com/infoaryan/Driver-Drowsiness-Detection/blob/master/driver_drowsiness.py
I'm marking the PR as invalid and closing it. If you want, you can take up some other issue and work on it. But, please refrain yourself from doing such things again.

**Pull request closed without merging**
