### PR TITLE
customer income analysis segmentation

### PR DESCRIPTION
**Pull request by dilroseR**
## Related Issue 

- Info about the related issue 

- [x] DevIncept Participant
- [x] Contributor

Closes: #505 

### Describe the add-ons or changes you've made

created a model which would classify customers into 5 categories
- low income low spending
- low income high spending
- medium income medium spending
- high income high spending
- low income low spending

## Type of change

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

## How Has This Been Tested?

Manually tested on my PC

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The project file should be as "customer_segmentation.ipynb"
In README.md, elaborate your conclusion more and mention an accuracy score you had gained through KMeans. Also in description, good overview of the project is needed.
And in project file, I guess you can do it more for this project. Correct me if i am wrong. The projects where you would do analysis is the place where you can play with data. 

Kindly do the above changes needed. And with respect to project file enhancement, if you are fine with what you had done. Then i will be merging it up. @dilroseR

**Comment by dilroseR** [comment]
> Changes to be done:
> The project file should be as "customer_segmentation.ipynb"
> In README.md, elaborate your conclusion more and mention an accuracy score you had gained through KMeans. Also in description, good overview of the project is needed.
> And in project file, I guess you can do it more for this project. Correct me if i am wrong. The projects where you would do analysis is the place where you can play with data.
> 
> Kindly do the above changes needed. And with respect to project file enhancement, if you are fine with what you had done. Then i will be merging it up. @dilroseR

i think we wont be able to find accuracy for kmeans because it is a grouping method and not a classifying type .It is supposed to find a grouping of data that maximizes between-clusters distances and from the plot it is clearly seen that all of them are clustered according to their types.
I made the other changes 👍

**Comment by dilroseR** [comment]
please let me know what you think!

**Comment by prathimacode-hub** [comment]
> please let me know what you think!

Ya, got your point. My bad, I though it was a prediction issue. Got confused. thanks for correcting. And yes, I shall check up with the PR. @dilroseR

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Good to see your pace and progress you had shown. Great work. Keep rocking. 📌👌👌@dilroseR

**Comment by dilroseR** [comment]
> Your PR is approved. Good to see your pace and progress you had shown. Great work. Keep rocking. 📌👌👌@dilroseR

Thankyou for motivating me! @prathimacode-hub

**Comment by prathimacode-hub** [comment]
You haven't filled up the PR from for this particular PR. And also make sure you add the right PR link to the form. Kindly do it. @dilroseR

**Comment by dilroseR** [comment]
> You haven't filled up the PR from for this particular PR. And also make sure you add the right PR link to the form. Kindly do it. @dilroseR

thankyou for letting me know. will do this right away

**Comment by prathimacode-hub** [comment]
> > You haven't filled up the PR from for this particular PR. And also make sure you add the right PR link to the form. Kindly do it. @dilroseR
> 
> thankyou for letting me know. will do this right away

Sure

**Pull request merged**
