### PR TITLE
Horses or Humans Classification

### PR DESCRIPTION
**Pull request by rammya29**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #192 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

**_Describe how it has been tested_**
 The model is tested in colab workspace, and it can also work in jupyter notebook.

**_Describe how have you verified the changes made_**
 I verified the changes by testing the model and plotted its accuracy and loss.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The project file should be titled as "horses_or_humans_classification.ipynb"
Add dataset or the link in "Dataset" folder. And also small README for dataset writing attributes of the dataset. 
Add all the imported libraries in "requirements.txt" file.

Kindly do these needful changes. @rammya29

**Comment by prathimacode-hub** [comment]
The project file should be titled as "horses_or_humans_classification.ipynb"
README.md should be elaborative enough. @rammya29

**Comment by rammya29** [comment]
which README mam?, and What else should be added in README?

**Comment by prathimacode-hub** [comment]
> which README mam?, and What else should be added in README?

Add short description about your project. @rammya29

**Comment by rammya29** [comment]
Now, mam?

**Review by prathimacode-hub — APPROVED** [review]
Fab work. Precise and perfect. You had nailed the project. Well done. 🎊👌🧨@rammya29

**Pull request merged**
