### PR TITLE
Salary prediction

### PR DESCRIPTION
**Pull request by Anshal55**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #221

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your README needs more elaboration. Add description. As well, add up the accuracies you had got. Add your conclusion and your name at the end. @Anshal55

**Comment by Anshal55** [comment]
@prathimacode-hub can I use a different dataset then , this one only has like 8 rows.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub can I use a different dataset then , this one only has like 8 rows.

If you want to, you can proceed. @Anshal55

**Comment by Manasi2001** [comment]
This looks perfect now @Anshal55. Extremely impressive work!! ✨✨

**Pull request merged**
