### PR TITLE
Olympic Medal Prediction 

### PR DESCRIPTION
**Pull request by Akash20x**
## Related Issue 

- Olympic Medal Prediction 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

Closes: #459 

### Describe the add-ons or changes you've made

I add a model which will predict whether an athlete will win a medal or not. 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It is tested on Google colab. 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Everything seems good, but I feel it would be better if you had shown some Data visualizations as well to get good understanding of the attributes before model training. So, let me know if you like me to merge it or would do the further changes. @Akash20x

**Comment by Akash20x** [comment]
> Everything seems good, but I feel it would be better if you had shown some Data visualizations as well to get good understanding of the attributes before model training. So, let me know if you like me to merge it or would do the further changes. @Akash20x


> Everything seems good, but I feel it would be better if you had shown some Data visualizations as well to get good understanding of the attributes before model training. So, let me know if you like me to merge it or would do the further changes. @Akash20x

OK i will data visualization also

**Comment by Akash20x** [comment]
@prathimacode-hub OK I will add data visualization also in the code file.

**Comment by Akash20x** [comment]
@prathimacode-hub I have done the required changes,
Please check my pull request

**Review by prathimacode-hub — APPROVED** [review]
This is a finest example of exclusive work. Very well justified and impressively showcased the visualizations. Good representations. Awesome. 🤩🤩🙌@Akash20x

**Pull request merged**
