### PR TITLE
KWOC 23 : Bangladesh Premier League Analysis

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## Related Issue 

- Analysis of the bangladesh premier league is done.

- [x] KWOC 2023 Participant 
- [x] Contributor

Closes: #issue number that will be closed through this PR
Closes: #627 

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Adding the dataset link just install the requirements.txt dependencies and start the model.
- Second method, i have made this model on google colab so just upload the file and link your kaggle.json file and run all the cells with GPU.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@prathimacode-hub please review this pr and requested to merge this pr under KWOC'23

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
That's a good choice of project. Keep contributing.

**Things to Add :**

Apply different analysis and visualizations that supports the problem statement in depth in your notebook file.
In README.md, list the type of visualizations along with  detailed conclusion along with insights gathered from the data and visual explorations in brief. Finally a proper conclusion according to your perspective.
Add visualization screenshots / images in "Images" folder in this project repository. @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@prathimacode-hub please again review this pr and requested to merge this pr under KWOC'23

**Comment by prathimacode-hub** [comment]
Can you add the information "Describe the add-ons or changes you've made" in your PR template? @Avdhesh-Varshney

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. The approach you followed and insights you had represented are so apt to the factor. Keep up the good work and enthusiasm higher. 🚀👍@Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
> Your PR is approved. The approach you followed and insights you had represented are so apt to the factor. Keep up the good work and enthusiasm higher. 🚀👍@Avdhesh-Varshney

> Can you add the information "Describe the add-ons or changes you've made" in your PR template? @Avdhesh-Varshney

@prathimacode-hub Thanks for merge this pr and your appreciations. I have added the description in the pr about my changes.

**Comment by prathimacode-hub** [comment]
Here is a small token of appreciation from my end : https://drive.google.com/file/d/1xRYhfkLXM5LfoJQ2CkcUTUxkREywaont/view?usp=sharing

To avail my Topmate Services on Data Science, take a sneak peek into this link : https://topmate.io/prathima_kadari

You can connect with me on Socials here :

LinkedIn - https://www.linkedin.com/in/prathima-kadari
Twitter - https://twitter.com/prathima_kadari

**Pull request merged**
