### PR TITLE
Advertisement Success Prediction

### LINKED ISSUE #216: Advertisement Success Prediction
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this dataset or any other [dataset](https://www.kaggle.com/fayomi/advertising) of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

### PR DESCRIPTION
**Pull request by Jagannath8**
## Advertisement Success Prediction

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

##Objective
The main objective of this project is to use different Machine Learning algorithms to predict Advertisement Success.

##Describe the add-ons or changes you've made
Added folders for Dataset, Model and Images for 'Advertisement Success Prediction'.

##How Has This Been Tested?
Manually tested.

Fixes #216

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The .ipynb file should be as "advertisement_success_prediction.ipynb".
Add a short description of the project in "README.md" file.

Kindly do this changes. @Jagannath8

**Comment by Jagannath8** [comment]
> The .ipynb file should be as "advertisement_success_prediction.ipynb".
> Add a short description of the project in "README.md" file.
> 
> Kindly do this changes. @Jagannath8

Done the necessary changes @prathimacode-hub mam.

**Review by prathimacode-hub — APPROVED** [review]
Your visualizations are fab. Great going. Wonderfully executed. 🎊🏷 @Jagannath8

**Comment by Jagannath8** [comment]
> Your visualizations are fab. Great going. Wonderfully executed. 🎊🏷 @Jagannath8

Thank you mam

**Pull request merged**
