### PR TITLE
Snapchat Filters

### LINKED ISSUE #485: Snapchat Filters
Title: I want to add a project for snapchat filters using Python
Name: Umesh Singh
Label: Feature Request

Define You-
- [x] LGM-SOC'21 Participant
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
I want to make a project for snapchat filters using python with the help of opencv, numpy, etc.

### PR DESCRIPTION
**Pull request by Umesh-01**
## Description

This fixes #485  

- [x] LGM-SOC'21 Participant 
- [x] Contributor

### Describe the add-ons or changes you've made

I have made a project on Snapchat filters which can help us to create different type of filters with the help of images. 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

## How Has This Been Tested?

Verified and tested manually.

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Have you used ML in this project? And the project structure is fine, but file formats are not appropriate. README lacks information and Your project file isn't sufficient. If ought to do with ML, it should be more elaborative. @Umesh-01

**Comment by Umesh-01** [comment]
yes @prathimacode-hub mam it's a kind of machine learning but the problem is that it is not a ML model using some type of data sets for doing it's work. And also I am learning ML so I don't have sufficient knowledge and dataset to create a model for this purpose.

> Have you used ML in this project? And the project structure is fine, but file formats are not appropriate. README lacks information and Your project file isn't sufficient. If ought to do with ML, it should be more elaborative. Kindly do these changes. @Umesh-01

**Comment by Umesh-01** [comment]
@prathimacode-hub mam kindly guide me what kind of changes I  have to do, so that I can make the required changes... :sweat_smile:

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

Add appropriate comments in code file to get good understanding of the project
The project file should be titled as "snapchat_filters.ipynb" which should be in "/Snapchat Filters/Model" folder
Also "README.md" should be in "Model" folder.
And README.md needs more details, you can check up with the template provided 

The project structure given here is completely different from other repo. Kindly do these needful changes. @Umesh-01

**Comment by Umesh-01** [comment]
> Changes to be done:
> 
> Add appropriate comments in code file to get good understanding of the project
> The project file should be titled as "snapchat_filters.ipynb" which should be in "/Snapchat Filters/Model" folder
> Also "README.md" should be in "Model" folder.
> And README.md needs more details, you can check up with the template provided
> 
> The project structure given here is completely different from other repo. Kindly do these needful changes. @Umesh-01

okk mam, I will do...

**Comment by Umesh-01** [comment]
now check it, @prathimacode-hub mam 🙂

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only change it needs, kindly add up the conclusion dervied out this project in conclusion section in README.md

@Umesh-01

**Comment by Umesh-01** [comment]
@prathimacode-hub mam I am having some more projects to work on, should I create different issues for these??
Like:
- changing background of any image,
- adding watermark on video or image, 
- and like blurring some part of images etc.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub mam I am having some more projects to work on, should I create different issues for these??
> Like:
> 
> * changing background of any image,
> * adding watermark on video or image,
> * and like blurring some part of images etc.

These won't come under this repo as long as ML is not used. If you are using ML for these above projects also make sure it isn't available in the repo done. These scripts might perfectly fit in "Awesome_Python_Scripts" projects only if issues are not done yet. So kindly decide with or without ML, based on that you can decide on the repo to choose for your contribution. @Umesh-01

**Review by prathimacode-hub — APPROVED** [review]
Whooa, your PR is approved. Great going. Keep shining up. 🙌🤩@Umesh-01

**Pull request merged**
