### PR TITLE
Diamond Price Prediction

### PR DESCRIPTION
**Pull request by Jagannath8**
## Diamond Price Prediction

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

##Objective
The main objective of this project is to use Machine Learning algorithms to predict price of Diamond .

##Describe the add-ons or changes you've made
Added folders for Dataset, Model, Backend and Images for 'Diamond Price Prediction'.

##How Has This Been Tested?
Manually tested.

Closes: #285

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Impressive work. That's awesome.

Only changes needed, instead of using just Logistic Regression and deploying a model. Add atleast 3 algorithms. Check through it and compare the accuracy and create a .pkl file with algorithm that has best accuracy. It would give efficient prediction and representation for this project. 
Also images you had added in "Image" folder instead add up in "Images" folder.
And in 'README.md' file, add all the accuracies and provide a good conclusion. 

Kindly do these needful changes. @Jagannath8

**Comment by Jagannath8** [comment]
I've done the necessary changes @prathimacode-hub mam

**Review by prathimacode-hub — APPROVED** [review]
Fab execution and great visualizations. Your work is exceptional. ✨✨✨@Jagannath8

**Comment by Jagannath8** [comment]
Thankuu @prathimacode-hub mam

**Pull request merged**
