### PR TITLE
Restaurant Recommendation System

### PR DESCRIPTION
**Pull request by abhisheks008**
## Related Issue #132 
Through this project, we are building a recommender system using Yelp Dataset.

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #132 

### Description
I wanted to build something that would be meaningful for people in their everyday lives. This ultimately led me to build a recommendation system model that could recommend people restaurants near their location based on restaurant reviews from other people, drawing on sentiment analysis that could potentially improve the recommendation suggestions that you see on common food delivery apps like Deliveroo, GrabFood, and FoodPanda.

## Type of change

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
The model has been tested using the Cosine similarity metric, which shows a very good score for this model. The score is nearly 1 out of 1.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by abhisheks008** [comment]
@prathimacode-hub I have created the PR for the issue #132. Please check it.

**Comment by Manasi2001** [comment]
Extremely impressive work @abhisheks008! The analysis is very nicely done and the notebook is awesome. 😀
Some very minor changes are needed to be done:
1. You can remove this file (it's just a replica of the README inside the Model folder):
image
2. The requirements.txt file needs to be made again. In this file we don't put the python code as such or write any other statements, we just mention the names of libraries with their versions like this:
image
The requirements file is needed when we go for deployment and if it's not is this format, then your application isn't going to work.

So just do these few tweaks, then you'll be good to go. 👍🏻

**Comment by abhisheks008** [comment]
@Manasi2001 updated all the required changes.

- [x] Deleting the unnecessary README.md file.
- [x] Updating the `requirements.txt` file.

Please check it!

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Amazing work showcased and impressive. The way you had differentiated from each other and deploying a model for user reviews is a wow factor. One of your finest PR. ✨✔👏@abhisheks008

**Pull request merged**
