### PR TITLE
Flight delay prediction

### PR DESCRIPTION
**Pull request by shivani6320**
## Related Issue : Flight Delay Prediction

- Info about the related issue : Aim is to predict future delays in flights.

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #31 

### Describe the changes you've made:
I have performed Exploratory Data Analysis to gain useful insights from the data. I cleaned the data by handling missing values. Created data visualizations to understand patterns better. I used Ensemble Modeling approach to draw best possible machine learning model suitable for data. Performed Feature Scaling on data before Model Creation. Compared various classification models like Logistic Regression, Naïve Bayes, K-Nearest Neighbors, Support Vector Machine to gain highest Model Performance. I used accuracy score as an evaluation matrix for the model.

## Type of change

What sort of change have you made:

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The project file should be titled as "flight_delay_prediction.ipynb
All files regarding dataset should be in "Dataset" folder
Also .csv file, you have mentioned it's above 100MB. Try to add it as zip file if possible else no issue this Dataset.md would be sufficient.
In README.md file of the project, kindly add all the 4 algorithms you had worked upon and as well add up the accuracies got from each model. Finally conclude it.

Kindly do the needful changes
@shivani6320

**Comment by shivani6320** [comment]
@prathimacode-hub changes has been done as per your suggestions. I already tried to zip the dataset file and upload but it still has size >100 MB, so I have kept it in dataset.md file in Dataset Folder. For rest of the changes, can you please check ?

**Review by prathimacode-hub — APPROVED** [review]
Yayy. Your PR is approved. Congrats and welcome to the repo officially. Wonderful work. Keep it up. 👏✨👍@shivani6320

**Comment by shivani6320** [comment]
@prathimacode-hub Thank you for approving my first PR :)

**Pull request merged**
