### PR TITLE
Stroke Prediction

### LINKED ISSUE #145: Stroke Prediction
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/fedesoriano/stroke-prediction-dataset) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

### PR DESCRIPTION
**Pull request by Jagannath8**
##Stroke Prediction

- [x] LGM-SOC'21 Participant 
- [x] Contributor

##Objective
The main objective of this project is to use different Machine Learning algorithms to predict Stroke.

##Describe the add-ons or changes you've made
Added folders for Dataset, Model and Images for 'Stroke Prediction'.

##How Has This Been Tested?
Manually tested.

Fixes #145

### CODE REVIEW

**Comment by Manasi2001** [comment]
Superb @Jagannath8!! Extremely impressive work. ✨✨ Good job!
Please add the requirements.txt file in the Model folder and I'll merge it :)

**Comment by Jagannath8** [comment]
> Superb @Jagannath8!! Extremely impressive work. ✨✨ Good job!
> Please add the requirements.txt file in the Model folder and then I'll merge it :)

Thank you @Manasi2001 
I've added the requirements.txt file

**Comment by Manasi2001** [comment]
Excellent!! Merging...

**Comment by prathimacode-hub** [comment]
You had raised your bar high. That was a wonderful progress shown by you. Looks perfect and clear. Awesome work shown. High applause for you. Keep shining. 👏👏👏@Jagannath8

**Comment by Jagannath8** [comment]
Thank you so much @prathimacode-hub mam 😁🤩

**Pull request merged**
