### PR TITLE
Tetris Object Counter

### PR DESCRIPTION
**Pull request by TusharAMD**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #50 

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

I have made all the changes that I was supposed to do and followed the correct pattern.
The models folder contain notebook and requirements file along with readme
And the Dataset contains all the images used in the project. There is no csv file for my project

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add your project name to your PR title. @TusharAMD

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes will be addressed tomorrow. By the way, the project file you add is just the code. You hadn't compiled it. @TusharAMD

**Comment by Manasi2001** [comment]
Some changes are required @TusharAMD:
1. Instead of adding your screenshots in Dataset/Screenshots, create a separate folder Images (directly in the 'Tetris Object Counter' folder) and put them there.
2. Run the notebook and then put that notebook in the Model folder.

Rest seems good to go!! 🎇

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

The images and screenshots added up as links in README.md file are external links. Kindly add the image links as a file path taken from this repo. Also add your name at the of the README file.

Kindly do this change. @TusharAMD

**Review by prathimacode-hub — APPROVED** [review]
Congrats. Welcome to the repo officially. Yayy. Your PR is approved. Well done and good choice of the project. Keep rising. 🎉👏👍@TusharAMD

**Pull request merged**
