### PR TITLE
German Traffic Sign Classification

### PR DESCRIPTION
**Pull request by Best-forever-003**
## Related Issue 

- Info about the related issue 
- Improvement of traffic system.

- [x] DevIncept Participant
- [x] Contributor

Closes: #issue number that will be closed through this PR
#408  

### Describe the add-ons or changes you've made
I have trained the model based on the dataset. This dataset has more than 50,000 images of 43 classes.

Give a clear description of what have you added or modifications made
I have tried to improve my model by training it with all advanced features.

## Type of change
Classifications of signals would be easier.

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Normal turning data and images to labels. Then training and testing it.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure given in README file of the project. You can check [here](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Dogecoin%20Price%20Prediction) on how a project folder should look like. Needs more files and follow the README template given. @Best-forever-003

**Comment by Best-forever-003** [comment]
@prathimacode-hub Madam, are things, okay now? Can you please confirm?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Add a README.md file in "Dataset" folder. It should have list of all details about dataset about attributes given
The README.md file present in project repo in not in right template. Follow the template given. It as well needs more information and also needs to be present in "Model" folder
Add "requirements.txt" file with list of libraries imported in this project
The project file name should be as "German_traffic_sign_classification.ipynb"

Kindly do the needful changes. You can refer this [repo](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Dogecoin%20Price%20Prediction). You can do this. @Best-forever-003

**Comment by Best-forever-003** [comment]
@prathimacode-hub, exactly done as per the guided author refference, Madam. Any more corrections?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
In README.md file, elaborate the conclusion, add the libraries and models you had used for this project and the image links in README.md are of user-images content, instead it should be the file path of the image present in this repo. @Best-forever-003

**Comment by Best-forever-003** [comment]
@prathimacode-hub, Updated Madam

**Review by prathimacode-hub — APPROVED** [review]
This is an outstanding work for your first PR. Congrats. Yayy. Your PR is approved. Welcome to the repo officially. 👏🎉👍@Best-forever-003

**Pull request merged**
