### PR TITLE
Tetris Object Counter

### PR DESCRIPTION
**Pull request by TusharAMD**
## Related Issue 

- This submission is for issue no 50 i.e. Creating Tetris block counter

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #50

### Changes made

In this project I have made a program that would detect the tetris tetriminos and will return the count.
There are 2 possible cases:
1. The tetriminos are complete i.e. they aren't broken during gameplay
2. Incomplete tetriminos which are reduced during game play
In the program we are successfully able to detect both the types of blocks in form of dictonary.

The program returns following:
1. No of Unoccupied Cells
2. A matrix representing the block it holds in form of pandas dataframe
3. No of cells each tetriminos occupy.
4. No of complete blocks.
5. No of incomplete blocks.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have manually counted the tetriminos and matched them with the output given by the program.
Till now its found to be correct and issues were debugged

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

Updated

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

All images and screenshots should be in "Images" folder
The readme file should be titled as "README.md"
Add the dataset (.csv) files in "Dataset" folder.
The "README.md" file should be the description of the project. You can refer other README's to know how it looks like. You had added an issue template here which is irrelevant.
.ipynb project file should be in "Model" folder. (.py files) are not accepted.
Add the libraries imported in your project in "requirements.txt" file.
.ipynb project file isn't opening up. Kindly reload it with correct file
The file name of the project should be as "tetris_object_counter.ipynb"
The project folder should be as "Tetris Object Counter"

Always follow the project structure and go through the guidelines so that your efforts won't go wasted.

Kindly do the needful changes. @TusharAMD

**Comment by prathimacode-hub** [comment]
No changes in your PR yet? Any update? @TusharAMD

**Comment by prathimacode-hub** [comment]
Why did you close the issue? @TusharAMD

**Comment by TusharAMD** [comment]
Actually I tried uploading file but it was giving me errors from past few days. I tried searching about it online but nothing worked. I thought by deleting the issue branch from my repsitory will solve it. I have made another pull request https://github.com/prathimacode-hub/ML-ProjectKart/pull/211
I have made all the required changes

**Comment by prathimacode-hub** [comment]
> Actually I tried uploading file but it was giving me errors from past few days. I tried searching about it online but nothing worked. I thought by deleting the issue branch from my repsitory will solve it. I have made another pull request #211
> I have made all the required changes

Ok

**Pull request closed without merging**
