### PR TITLE
Customer Segmentation Analysis using ML

### PR DESCRIPTION
**Pull request by theanshulcode**
I am uploading the readme.md file and will be updating it step by step according to my project progress.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Sure, carry on. But make sure you raise the issue first, before you create a pull request. So that when you create  pull request, you can assign the issue number (#issuenumber) here in commit mesage. That would be helpful as a reference issue to this PR. Always create a new issue stating about the project you are going to contribute. Can you raise a issue now? So that i could assign you to the issue. That would be very much easier. Letting you know about how things work especially in open source. Other than that all cool, good to see you contribute a new script once again. Hope it's helping you get better with things. 🙂@theanshulcode

**Comment by theanshulcode** [comment]
> Sure, carry on. But make sure you raise the issue first, before you create a pull request. So that when you create pull request, you can assign the issue number (#issuenumber) here in commit mesage. That would be helpful as a reference issue to this PR. Always create a new issue stating about the project you are going to contribute. Can you raise a issue now? So that i could assign you to the issue. That would be very much easier. Letting you know about how things work especially in open source. Other than that all cool, good to see you contribute a new script once again. Hope it's helping you get better with things. 🙂@theanshulcode

Ya sure I am raising the issue. Sorry for the mistake @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Never mind. No issues. This is how you learn and grow. I am happy to correct you. Any queries, don't hesitate to ask. @theanshulcode

**Comment by prathimacode-hub** [comment]
Hey, thanks for creating a pull request. But there is a merge conflict arised in PR. Do solve these conflicts from your end. Else I won't be able to get access to merge it. The main reason being the changes you made in main README.md file of the project. This change brought a conflict. If it's kinda tough for you to solve the conflict, do raise a new PR with the necessary project files you had included. Any questions, feel free to ask. @theanshulcode

**Comment by prathimacode-hub** [comment]
Ok, got you. I could see the project title for the repository, so i thought it did belong here. Anyways keep ur own pace. No issue. @theanshulcode

**Pull request closed without merging**
