### PR TITLE
Colour Identification using Machine Learning

### PR DESCRIPTION
**Pull request by psyduck1203**
## Colour Identification using Machine Learning 
A very common task in Computer Vision is based on identifying colours. More generally, a fascinating aspect of learning is that sometimes we know things but we can’t explain them. For example, if I ask you to describe me the “red colour” your only option is to show me a red object, but you can’t really explain what “red” is. For this reason a certain effort is necessary to transmit the definition of a colour to a computer.

- [X] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #43 

### Describe the add-ons or changes you've made
I have used OpenCV and Pandas library to choose a point on any particular image and calculate the RGB of that point and match it with the nearest colour in the dataset to predict the colour.

### About the Dataset
Colors are made up of 3 primary colors; red, green, and blue. In computers, we define each color value within a range of 0 to 255. So in how many ways we can define a color? The answer is 256256256 = 16,581,375. There are approximately 16.5 million different ways to represent a color. In our dataset, we need to map each color’s values with their corresponding names. But don’t worry, we don’t need to map all the values. We will be using a dataset that contains RGB values with their corresponding names.

### Libraries Used
- OpenCV
- Pandas

### Checklist:
- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### Screenshots 
 Original | 
 :--------------------: | 
pic1 
Updated |
result3

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly elaborate your README file. @psyduck1203

**Comment by psyduck1203** [comment]
Okay I'll add the results in README but what elaboration is required? P.S.: I have mentioned the problem statement and the solution, what else is required?

**Comment by prathimacode-hub** [comment]
> Okay I'll add the results in README but what elaboration is required? P.S.: I have mentioned the problem statement and the solution, what else is required?

Yup, do these changes. With respect to elaboration in your README file. There is a template in the README file of this repository. It will clear out your queries. Don't remove the descriptions you had Already given. Just add whatever you had missed adding in your README file of your project.

@psyduck1203

**Comment by psyduck1203** [comment]
@prathimacode-hub I have added the required changes. Please review and merge the PR.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. It will be merged soon. Well done. 👏✔@psyduck1203

**Pull request merged**
