### PR TITLE
KWOC 2023 : Gun Detection using YOLOv5

### PR DESCRIPTION
**Pull request by Pranay38**
## Related Issue 

- Info about the related issue 

- [x] KWOC 2023 Participant 
- [x] Contributor

Closes: #624 

#### Overview

- This pull request introduces an initial implementation of a gun detection project using YOLOv5, focusing on building a robust system to detect firearms within images. This project marks the inception of a dedicated solution for firearm detection.

 #### Project Features

**Gun Detection Model:**
Utilizes YOLOv5s architecture for object detection, specifically tailored for identifying guns within images.

**Training on Custom Dataset**:
Trains the model on a custom dataset containing firearm images to enable accurate detection.

**Functionalities Included:**
Incorporates functionalities for image processing, model training, and inference to detect guns within images.

**Purpose and Impact**

**Purpose:** This initial implementation aims to lay the groundwork for a reliable gun detection system, enhancing safety measures by automating firearm identification in images.

**Impact:** Provides a foundational structure for further development and improvement in firearm detection capabilities.
Changes Introduced

### New Project Initialization:

- Adds the initial set of files, including scripts, model configurations, and dataset placeholders.

## Type of change

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Model Training and Validation:
Trained and validated the gun detection model using a custom dataset to ensure accuracy and convergence.

### Manual Review:
Manually reviewed added files, scripts, configurations, and dataset placeholders for correctness and presence.

### Functional Validation:
Tested and confirmed operational functionalities for image processing, model training, and inference.

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — COMMENTED** [review]
Just final changes to be done. Do it in this PR itself.
Rename dataset folder as "Dataset". And in README.md file in Dataset folder include the list of parameters used for this problem statement. @Pranay38

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Well done. Choice of your project is wow. Kudos on taking this initiative.⚡👌 @Pranay38

**Comment by prathimacode-hub** [comment]
Here is a small token of appreciation from my end : https://drive.google.com/file/d/1cjTeHwuNrXgvBEIuTgYeRn23UbZMNMRc/view?usp=sharing

To avail my Topmate Services on Data Science, take a sneak peek into this link : https://topmate.io/prathima_kadari

You can connect with me on Socials here :

LinkedIn - https://www.linkedin.com/in/prathima-kadari
Twitter - https://twitter.com/prathima_kadari

@Pranay38

**Comment by Pranay38** [comment]
Thank you ma'am @Pranay38

**Comment by Pranay38** [comment]
Thank you ma'am @prathimacode-hub

**Pull request merged**
