### PR TITLE
Private Companies Prediction

### PR DESCRIPTION
**Pull request by aryantiwari10**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

Closes: #470

### Describe the add-ons or changes you've made

PROJECT TITLE : Private Companies Prediction

GOAL : To predict the number of the private limited companies.

DATASET : https://www.kaggle.com/aryantiwari123/privated-limited-companiescsv

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the Private Companies dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model prediction part I used different machine learning algorithms . In each algorithm I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset . During the model prediction I got different accuracies from different models , I got the highest accuracy of 100 % using the Random Forest Classifier which is quite well for the given Private Companies dataset . While the other model accuracies can be increased more using the hypertuning . Some plots which I used for visualizing the dataset are Histogram , Barplot , Boxplot, Heatmap , Scatter plot , Pairplot , Jointplot etc.

LIBRARIES:

PANDAS

NUMPY

MATPLOTLIB

SEABORN

SCIPY

SKLEARN

CONCLUSION :

So we get a good accuracy score of 100 % using Random Forest Classifier and Ada Boost Classifier.

The accuracy of other models can be increased by Hypertuning.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by Manasi2001** [comment]
Super awesome work @aryantiwari10! Always nailing the projects. 😃

**Comment by aryantiwari10** [comment]
Thank you so much 😃😃

**Comment by prathimacode-hub** [comment]
Impressive work as expected, well done. 👌🙌@aryantiwari10

**Comment by aryantiwari10** [comment]
Thank you so much!!

**Pull request merged**
