### PR TITLE
Dog breed identification

### PR DESCRIPTION
**Pull request by Anshal55**
## Related Issue 

- Working model and Deployment of Dog breed Identification

- [x] LGM-SOC'21 Participant 
- [] Contributor

### Describe the add-ons or changes you've made
Built a model and deployed it using flask.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have tested it manually of a lot of images.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes needed to be done:

The project folder should be titled as "Dog Breed Identification"
The project files should be in "Model" folder
Images and screenshots in "Images" folder
Create a "Dataset" folder and add dataset of dog breed identification used.
The readme file of the project should be titled as "README.md"

Kindly do the needful changes. @Anshal55

**Comment by prathimacode-hub** [comment]
Hey, you shouldn't close the PR from your end. This PR won't count. Kindly reopen the PR. You're not allowed to make any changes. @Anshal55

**Comment by Anshal55** [comment]
Sorrry for that I hadn't added folders I will create a final pull request in few minutes. @prathimacode-hub

**Comment by Anshal55** [comment]
Or should I just restore?

**Comment by prathimacode-hub** [comment]
> Or should I just restore?

Yes, restore it. There is option down to the PR. It shows reopen PR. After you reopen, add the needed files and folders. @Anshal55

**Comment by Anshal55** [comment]
Okay will do that.

**Comment by prathimacode-hub** [comment]
You have conflicts in your PR. You shouldn't change any .github files. @Anshal55

**Comment by Anshal55** [comment]
Yeah it was a mistake Can I  just initialize a different branch an delete this pull request and branch.

**Pull request closed without merging**
