### PR TITLE
Hotel Booking Prediction

### PR DESCRIPTION
**Pull request by aryantiwari10**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

Closes: #395

### Describe the add-ons or changes you've made

In this project first I performed a exploratory data analysis on the hotel booking dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model prediction part I used total 9 machine learning algos . In each algo I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset .

MODELS USED : I used total 9 machine leaning algos in the dataset

Logistic Regression
KNeighborsClassifier
DECISION TREE CLASSIFIER
Random Forest Classifier
AdaBoostClassifier
Gradient Boosting Classifier
XGBClassifier
ExtraTreesClassifier
Bagging Classifier

LIBRARIES NEEDED :
Pandas
Numpy
Matplotlib
Seaborn
Scipy
Sklearn

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by Manasi2001** [comment]
Nice beginning @aryantiwari10! Just do the changes that you discussed with me.

**Comment by Manasi2001** [comment]
Extremely impressive work @aryantiwari10!! Kudos to you for completing your first project here. ✨✨

**Review by prathimacode-hub — COMMENTED** [review]
This was an outstanding work. Congratulations on making your first PR. Yayyy. Welcome to the repo officially. Very well represented the project. Can't wait to see the upcoming projects coming from you. ✨👏🎉@aryantiwari10

**Comment by aryantiwari10** [comment]
Thank you for your support!

**Pull request merged**
