### PR TITLE
Fashion MNIST Classification

### PR DESCRIPTION
**Pull request by psyduck1203**
## Fashion MNIST Classification 

- Info about the related issue 

- [X] LGM-SOC'21 Participant 
- [X] Contributor

Closes: #155 

### Describe the add-ons or changes you've made
Implemented three models - KNN, Logistic Regression and SVM and classified Fashion MNIST dataset.

## Checklist:
- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

## Screenshots 

 KNN Accuracy | SVM Accuracy
 :--------------------: |:--------------------:
KNN | SVM |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

- Add description of your project in your README file. Instead of adding screenshots, add all the accuracies you had got through the algorithms used and derive a conclusion out of it and your name at the end of your file in README file of your project.
- The project folders should be as "Dataset and "Model"
- The "Dataset" folder should have the dataset included along with short README of your dataset. The "README" file of the Dataset should have attributes listed out and state the description of dataset.
- The project files doesn't show your project name. Instead of working on separately for each algorithm you choose, you can do the necessary things up in a single file.
- The project file should be titled as "fashion_mnist_classification.ipynb".
- If you want to provide project files as individual algorithms, you can write up as "fashion_mnist_classification_svm.ipynb" etc and vice versa.
- The screenshots you added up in README.md file can be uploaded in "Images" folder and direct them to README file of your project.
- Also in "requirements.txt", add libraries imported in your project.

Always follow the project structure and contributing guidelines given. Else your efforts might go wasted. Kindly follow the changes asked for. @psyduck1203

**Comment by psyduck1203** [comment]
The Dataset used i.e Fashion MNIST Dataset is of 36MB and github only allows to upload upto 25MB. I tried spliting the training and testing dataset and then uploading the file but it fails. I have mentioned the dataset link in the README. Ill do the remaining things.

**Comment by prathimacode-hub** [comment]
> The Dataset used i.e Fashion MNIST Dataset is of 36MB and github only allows to upload upto 25MB. I tried spliting the training and testing dataset and then uploading the file but it fails. I have mentioned the dataset link in the README. Ill do the remaining things.

Ok sure, go ahead. @psyduck1203

**Comment by Manasi2001** [comment]
@psyduck1203 updates? We haven't heard from you in a long time.

**Comment by psyduck1203** [comment]
@prathimacode-hub @Manasi2001. You can review and merge the PR. Sorry for the delay!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your README.md needs more elaboration. And as well, you haven't added up the evaluation values of the agorithms implemented neither it doesn't show up any conclusion in your file
Also no description of the project. And your name at the end of the file. Kindly add up these necessary changes. @psyduck1203

**Comment by Manasi2001** [comment]
Are you willing to do the changes @psyduck1203 or not? Please keep us updated with your work.

**Comment by psyduck1203** [comment]
I have done the required changes.

**Comment by Manasi2001** [comment]
Good to go now @psyduck1203. 🎉🎉

**Pull request merged**
