### PR TITLE
Crypto Research and Stocks Automation Analysis

### PR DESCRIPTION
**Pull request by mv1249**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

Closes: #476 

### Describe the add-ons or changes you've made

Scrapped the data from GoogleNews/Yahoo Finance and passed it to the text-summarization model
and then performed the sentiment analysis on the summarised text

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Yes it has been tested,and the results are exported to the csv file

Describe how it has been tested

For the start the whole process was trained on 50 samples,summarizing and performing sentiment analysis on 50 samples
were made,then after i have tested it for 180+ samples 3 stocks majorly 180+news feeds in total were scrapped and summarised
and then the results were exported to the csv file.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow proper format given in README file fo the project. @mv1249

**Comment by prathimacode-hub** [comment]
Why r u doing changes to the README file of this project. It's showing conflicts. I asked for you to follow the project structure and details given in README file of the project and implement it in your project. @mv1249

**Comment by prathimacode-hub** [comment]
No update from you and your PR shows conflicts because of the changes you tried to make in the README file of the main repo. o correct it from your end and address the changes asked. @mv1249

**Comment by mv1249** [comment]
> No update from you and your PR shows conflicts because of the changes you tried to make in the README file of the main repo. o correct it from your end and address the changes asked. @mv1249



> No update from you and your PR shows conflicts because of the changes you tried to make in the README file of the main repo. o correct it from your end and address the changes asked. @mv1249

ma'am comment has been updated : 


## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

Closes: #issue number that will be closed through this PR

Issue number : #482 

### Describe the add-ons or changes you've made

Scrapped the data from GoogleNews/Yahoo Finance and passed it to the text-summarization model
and then performed the sentiment analysis on the summarised text

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Yes it has been tested,and the results are exported to the csv file

Describe how it has been tested

For the start the whole process was trained on 50 samples,summarizing and performing sentiment analysis on 50 samples
were made,then after i have tested it for 180+ samples 3 stocks majorly 180+news feeds in total were scrapped and summarised
and then the results were exported to the csv file.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

**Comment by prathimacode-hub** [comment]
You have merge conflicts. You have changed things in README  file of this main repository. Until you clear that, I won't be able to check on it. @mv1249

**Comment by prathimacode-hub** [comment]
Also your project PR is not in right format, kindly check that. @mv1249

**Comment by prathimacode-hub** [comment]
Its been 11 days and no update from you yet. If you don't respond within 2 days, unfortunately I would have to close this PR. @mv1249

**Comment by prathimacode-hub** [comment]
9th is the last date to accept PR's. If you wouldn't do it by then, obviously you can submit later but points won't be counted towards DCP program. @simranquirky

**Comment by prathimacode-hub** [comment]
Files are still conflicting. DCP program is done, so unfortunately its over. And you hadn't done the changes yet. But if you want you can express your interest again and work if you want to. For now this PR is closed and issue is unassigned. Max time for any PR once issue is assigned is 5days. You had taken a longer time and helding it up long time is never right. Work on it only when you could give you time to it. @mv1249

**Comment by prathimacode-hub** [comment]
And one more thing I had noticed that file you added up in your PR are no where relevant to your issue. It's all about covid, vaccination and IPL which as far as my knowledge won't come up in this analysis. @mv1249

**Comment by mv1249** [comment]
I apologize for all my mistakes ma'am I will take your points into
consideration

**Comment by prathimacode-hub** [comment]
Ok, all the best. @mv1249

**Pull request closed without merging**
