### PR TITLE
Lego minifigures

### PR DESCRIPTION
**Pull request by Isha307**
## Related Issue 

model for Lego minifigures

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: [#151](https://github.com/prathimacode-hub/ML-ProjectKart/issues/151)

### Describe the add-ons or changes you've made

Created Model

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The project file should be titled as "lego_minifigures.ipynb"
You had used CNN here, do you want to add upon any other model along with it?

Kindly do these changes. 
@Isha307

**Comment by Isha307** [comment]
> Changes to be done:
> The project file should be titled as "lego_minifigures.ipynb"
> You had used CNN here, do you want to add upon any other model along with it?
> 
> Kindly do these changes.
> @Isha307

I have made the changes. Do tell me if more changes are required.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Instead of adding a screenshot of epoch in README.md. Write it up in words for conclusion. @Isha307

**Comment by Manasi2001** [comment]
Fabulous work @Isha307!! So well done. 💯

**Comment by prathimacode-hub** [comment]
Impressive work showcased. Wow. Appreciate your choice of the project. 👌🎊@Isha307

**Pull request merged**
