### PR TITLE
Fragnance Price Prediction 

### PR DESCRIPTION
**Pull request by aryantiwari10**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

Closes: #444

### Describe the add-ons or changes you've made
PROJECT TITLE : Fragnance Price Prediction

GOAL : To predict the price of the fragnances .

DATASET : https://www.kaggle.com/aryantiwari123/pricelistcsv

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the Pricelist dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model prediction part I used total 10 machine learning algos . In each algo I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset .

MODELS USED : I used total 10 machine leaning algos in the dataset

Logistic Regression : 62.40 %

KNeighborsClassifier : 60.46%

SVC : 62.45 %

Naive Bayes : 60.26%

DECISION TREE CLASSIFIER : 70.07%

RandomForestClassifier : 74.77%

AdaBoostClassifier : 34.29%

Gradient Boosting Classifier : 73.90%

ExtraTreesClassifier : 78.7%%

Bagging Classifier : 98.47%

LIBRARIES:

PANDAS

NUMPY

MATPLOTLIB

SEABORN

SCIPY

SKLEARN

CONCLUSION :

So we get a good accuracy score of 98.47 % using the Bagging Classifier.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README.md file should be more elaborative. Be briefer about your project. Your notebook is totally fab. Just look through the template. 
@aryantiwari10

**Comment by aryantiwari10** [comment]
Hey can you please merge it to the main I have made the changes

**Comment by Manasi2001** [comment]
Perfectly done @aryantiwari10. Analysis is superb. Keep it up! 🎉

**Comment by aryantiwari10** [comment]
Thank You so much 😃

**Comment by prathimacode-hub** [comment]
You're amazing with the work you showcase. It's a fab notebook. 🤩👌@aryantiwari10

**Comment by aryantiwari10** [comment]
Thank you for your support!

**Pull request merged**
