### PR TITLE
Zoo-Animal-Classification

### LINKED ISSUE #154: Zoo Animal Classification
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/uciml/zoo-animal-classification?select=class.csv) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

### PR DESCRIPTION
**Pull request by anishamurmu13**
## zoo animal classification

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

##Objective
The main objective of this project is to use different Machine Learning algorithms to predict zoo animals.

##Describe the add-ons or changes you've made
Added folders for Dataset, Model for 'Zoo Animal Classification'.

##How Has This Been Tested?
Manually tested.

Fixes #154

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done : 

The readme files should be titled as "README.md"
The project folder should be titled as "Zoo Animal Classification"
The project file should be titled as "zoo_animal_classification.ipynb
Add the libraries imported in "requirements.txt" file.

Always follow the project structure given. Kindly do these changes. @anishamurmu13

**Comment by anishamurmu13** [comment]
I have made the necessary changes please review it @prathimacode-hub mam.

**Review by prathimacode-hub — APPROVED** [review]
Welcome to the repo officially. Yayy. Your PR is approved. Congrats. Well done. That was a good work done. Keep rising. 🎉✨👍@anishamurmu13

**Comment by anishamurmu13** [comment]
> 
> 
> Welcome to the repo officially. Yayy. Your PR is approved. Congrats. Well done. That was a good work done. Keep rising. 🎉✨👍@anishamurmu13

Thank you mam.

**Pull request merged**
