### PR TITLE
issue#12 speech emotion recognition added

### PR DESCRIPTION
**Pull request by sy07**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #[issue number that will be closed through this PR]

### Describe the add-ons or changes you've made

I have explored the audio files and trained data on two algorithms which gives accuracy 70-76%

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have tested the algorithms on 30% data of the provided RAVDESS dataset.
MLP classifier gives accuracy of 76% and SVM model gives accuracy of 68%. 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by Manasi2001** [comment]
@sy07 very good job on making your first PR here! Just add the requirements.txt file in Model folder as well. And try to add some descriptive comments in your notebook. It will then become more easily understandable :)

**Comment by sy07** [comment]
> @sy07 very good job on making your first PR here! Just add the requirements.txt file in Model folder as well. And try to add some descriptive comments in your notebook. It will then become more easily understandable :)

Okay mam

**Comment by sy07** [comment]
> @sy07 very good job on making your first PR here! Just add the requirements.txt file in Model folder as well. And try to add some descriptive comments in your notebook. It will then become more easily understandable :)

Mam i have pushed the required changes you have asked for.

**Comment by Manasi2001** [comment]
@sy07 the requirements file still needs a little bit of tweaking. Actually this type of file is required when we go for model deployment, so it needs to be in the right format otherwise your application won't run. Check out this [video](https://www.youtube.com/watch?v=23sp3cj5Pnc). Don't need to go through all of it, there's a part where he tells you how you can obtain the requirements.txt file directly. You don't need to write it yourself. Try it. If you still face any issues, ping me and I'll guide you.

**Comment by Manasi2001** [comment]
Extremely good @sy07!! Nicely executed. ✨

**Comment by Manasi2001** [comment]
You can take up other issues now.

**Comment by prathimacode-hub** [comment]
Great going. Keep it up. Wonderful work. 🙌👍@sy07

**Pull request merged**
