### PR TITLE
Diabetes Prediction

### PR DESCRIPTION
**Pull request by arihantrode89**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

Closes: #433 

### Describe the add-ons or changes you've made
PROJECT TITLE : Diabetes Prediction

GOAL : To predict whether a person has diabetes or not

**What I had done :**  As you know I have created issue regarding the Data processing which was not taken place in previous notebook.I found that in dataset some features values are 0 such as BloodPressure , BMI , Skinthickness is 0 which is practically not possible. So I replaced the 0 value by the median of that particular features and then split those data into training and testing set. I trained this training data on some of classication model which include Logistic Regression , Decision Tree Classifier , SVM and Random Forest Classifier
         

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
--> This can be tested as we know that SkinThickness ,BMI, BloodPressure Can't be zero

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Add the dataset you had used to "Dataset" folder. 
Add a .pkl file in "Model" folder
The .ipynb file should be as "diabetes_prediction_enhanced.ipynb"
Check through if the libraries you had included in the project are added up in "requirements.txt" flle else add them
And README.md needs to be more elaborative, Few things missing. Also add a description about the project.

Kindly do these changes. @arihantrode89

**Comment by arihantrode89** [comment]
Yes sure.

**Comment by arihantrode89** [comment]
@prathimacode-hub  I made your requested changes

**Comment by Manasi2001** [comment]
Hey @arihantrode89, some small changes are still required:
1. Delete these:
image
2. The dataset folder is till not there. Please add that with your dataset in it.
3. Rename this as 'README.md' only.
image

Do these necessary changes and I think it should be good to go then :)

**Comment by arihantrode89** [comment]
Okay thanks for you suggestions @Manasi2001

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The requirements should be in "requirements.txt" file
Add your name at the end of the README.md file. @arihantrode89

**Review by prathimacode-hub — APPROVED** [review]
Hey, welcome to repo officially. Congrats on your first PR. PR is approved. Yayy. This was a wonderful kick start from you. Get going. ✨🤩👏@arihantrode89

**Comment by arihantrode89** [comment]
Thank you so much @prathimacode-hub . This is so special for me because this is my first OPEN SOURCE contribution. Thanks for always helping me out though out the entire process.

**Comment by prathimacode-hub** [comment]
Most welcome and keep contributing. Enjoy your open source journey ahead. @arihantrode89

**Comment by arihantrode89** [comment]
Yeah sure 💯

**Pull request merged**
