### PR TITLE
Added Emotion Detection using ML

### PR DESCRIPTION
**Pull request by NEERAJAP2001**
## Related Issue 

- Added Emotion Detection using ML

- [x] Hacktoberfest2021 Participant 
- [ ] Contributor

Fixes: #572 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Refer screenshot

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

The .ipynb file code blocks aren't compiled
Add dataset link in your README file
Change the title of images to "Images" folder
In README.md, add models and libraries used, also provide all the accuracies you had received for all the models and overall conclusion.

Kindly work on it. @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Okay @prathimacode-hub , I'm working on them

**Comment by NEERAJAP2001** [comment]
Actually, it's crashing due to overhead, I'll come back with a new PR in some time is that okay? @prathimacode-hub

**Comment by prathimacode-hub** [comment]
By when are you expected to do? Fest is about to end? @NEERAJAP2001

**Pull request closed without merging**
