### PR TITLE
Amazon Alexa Reviews

### PR DESCRIPTION
**Pull request by sonaliBedade**
## Amazon Alexa Reviews

- Predicts feedback of users according to the input features like reviews, variation

- [x] LGM-SOC'21 Participant 

Closes: #26 

### Description:
The model categorizes the feedback of users into two classes ie. either 0 or 1 based on the user reviews, variation and star ratings of the product.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
The data was splitted into test data and training data. It has been tested using the test data.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Hey, you can add up atleast 1 more algorithm  to know the good check on the efficiency. Since it's a reviews project, you can try to show up the analysis of the reviews using different visualizations ad parameters. And also screenshot should be in "Images" folder. Don't forget to change the PR title to your project name. Kindly do these changes. @sonaliBedade

**Comment by Manasi2001** [comment]
Hey @sonaliBedade, what's the update on this PR? Are you not willing to work more on it? We haven't heard from you in 9 days.

**Comment by sonaliBedade** [comment]
I'm stuck on an error and not able to solve it

**Comment by prathimacode-hub** [comment]
> I'm stuck on an error and not able to solve it

Is all going fine? @sonaliBedade

**Comment by prathimacode-hub** [comment]
No reply from you yet. @sonaliBedade

**Comment by sonaliBedade** [comment]
Sorry for replying late, I was out of town for the past few days. I'm giving the issue a last try if even that doesn't work out well then I'll let you know by tomorrow

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add up the accuracies you had recieved for each model, elaborative conclusion and your name at the end of the README.md file. That's it and you will be done. @sonaliBedade

**Review by prathimacode-hub — APPROVED** [review]
Yayy, welcome to this repo. Congo, well done. I highly appreciate your spirits to put your efforts and not give up. Impressive work. Great going. ✨🤩🙌@sonaliBedade

**Comment by sonaliBedade** [comment]
Thank you so much!! @prathimacode-hub

**Pull request merged**
