### PR TITLE
Extending "Look Through The Kart Of Amazing Projects" section in README.md file

### PR DESCRIPTION
**Pull request by jannatulferdaws**
## Related Issue 
- Info about the related issue 
- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #209

### Describe the add-ons or changes you've made
I have extended the "Look Through The Kart Of Amazing Projects" section in README.md file.
There are 109 projects in this repository. But there were only 23 projects in "Look Through The Kart Of Amazing Projects" sections. I have added the new projects in this section in alphabetic order with a little description. Also deleted the repetitive projects. Basically this is a documentation change.
## Type of change
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Have you done any changes in Stars, Quassar's classification. @jannatulferdaws

**Comment by jannatulferdaws** [comment]
No. I did not touch any folder apart from README.md file. @prathimacode-hub

**Comment by prathimacode-hub** [comment]
> No. I did not touch any folder apart from README.md file. @prathimacode-hub

But it's showing changes in that repo. And also the README.md file, can you share the screenshot from your forked repository?. It's not showing up in table template. @jannatulferdaws

**Comment by jannatulferdaws** [comment]
Wait a minute. I am giving the screenshot.

**Comment by jannatulferdaws** [comment]
I have identified the problem. It will take some time. Sorry about
that.This is my first time.

**Review by prathimacode-hub — APPROVED** [review]
Perfect. Thanks for this initiation and helping me out. Glad you got this ready as said. Congrats. Your first PR is approved. Keep it up. Yayy. ✨🎉👍@jannatulferdaws

**Comment by prathimacode-hub** [comment]
> I have identified the problem. It will take some time. Sorry about that.This is my first time. 

That's Ok. It happens, but you got the problem and corrected it right. Proud of you. @jannatulferdaws

**Pull request merged**
