### PR TITLE
IPL Score Prediction

### PR DESCRIPTION
**Pull request by SuryanshNaugraiya**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #36 

### Describe the add-ons or changes you've made

I have added an end to end project folder named "IPL" from scratch.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
After creating a project, i have run it and it is working perfectly fine.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure given. Give proper title to your PR. It's not int the right format, project should be. Kindly correct all the changes. Even your PR template has no information about your project. @SuryanshNaugraiya

**Comment by SuryanshNaugraiya** [comment]
@prathimacode-hub changed the title

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
No, it's not followed yet. See the project structure given in README.md file of the project. And correct me if i am not right. @SuryanshNaugraiya

**Comment by SuryanshNaugraiya** [comment]
TITLE : IPL SCORE PREDICTION

GOAL : the goal of this project is to predict the score of an innings in an IPL match

DATASET :  https://www.kaggle.com/laxmena/ipl-dataset-2020-season-included

I have implemented an end to end project 
Its frontend is implemented using html5 and css3
Its backend is designed using flask

MODELS USED : I have used all the regression techniques like linear regression, decision tree regression, support vector regressor etc, to check that which model is performing best in our dataset
 
LIBRARIES NEEDED : numpy, pandas, matplotlib, sklearn

INCLUSION OF SCREENSHOT : the screenshots are attached below

CONCLUSION : this project has a practical application , it can be used to predict the score of innings of IPL match in advance so users can use it. 

Screenshot (254)
Screenshot (255)
Screenshot (256)
Screenshot (257)
Screenshot (258)
Screenshot (259)
Screenshot (263)
Screenshot (264)
Screenshot (265)
Screenshot (266)
Screenshot (267)
Screenshot (268)

**Comment by SuryanshNaugraiya** [comment]
@prathimacode-hub please check it and merge it

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
No it's not in right project structure yet. You can review other projects to see how structure looks like. Also I have mentioned everything about structure to follow in README.md file of this project.  There is no proper project title for your project as well. @SuryanshNaugraiya

**Comment by prathimacode-hub** [comment]
> TITLE : IPL SCORE PREDICTION
> 
> GOAL : the goal of this project is to predict the score of an innings in an IPL match
> 
> DATASET : https://www.kaggle.com/laxmena/ipl-dataset-2020-season-included
> 
> I have implemented an end to end project
> Its frontend is implemented using html5 and css3
> Its backend is designed using flask
> 
> MODELS USED : I have used all the regression techniques like linear regression, decision tree regression, support vector regressor etc, to check that which model is performing best in our dataset
> 
> LIBRARIES NEEDED : numpy, pandas, matplotlib, sklearn
> 
> INCLUSION OF SCREENSHOT : the screenshots are attached below
> 
> CONCLUSION : this project has a practical application , it can be used to predict the score of innings of IPL match in advance so users can use it.
> 
> Screenshot (254)
> Screenshot (255)
> Screenshot (256)
> Screenshot (257)
> Screenshot (258)
> Screenshot (259)
> Screenshot (263)
> Screenshot (264)
> Screenshot (265)
> Screenshot (266)
> Screenshot (267)
> Screenshot (268)

If you need help you can ask, I shall guide you. @SuryanshNaugraiya

**Comment by SuryanshNaugraiya** [comment]
hey, @prathimacode-hub i am not getting , like what changes i have to make and where to do the changes, and i am sorry to say that i will not be able to make the changes because yesterday i got the mail from infosys , that i have my interview scheduled this week, so i am busy in preparing for interview, so can you please merge it in your repo. I have uploaded all the files and its simple you have to just open it in jupyter notebook and run the app.py file, the code will run.
And if you say, then i can also add my conid-19 analysis project in your repo today iself, it is also an end to end project.

**Comment by prathimacode-hub** [comment]
> hey, @prathimacode-hub i am not getting , like what changes i have to make and where to do the changes, and i am sorry to say that i will not be able to make the changes because yesterday i got the mail from infosys , that i have my interview scheduled this week, so i am busy in preparing for interview, so can you please merge it in your repo. I have uploaded all the files and its simple you have to just open it in jupyter notebook and run the app.py file, the code will run.
> And if you say, then i can also add my conid-19 analysis project in your repo today iself, it is also an end to end project.

You're not getting my point, it has some project structure to follow. Take your time, but provide right format. You just have to upload the files according to the pattern followed. Projects can't be added without structure. Ok. you have interview. I understand. All the best. Is covid-19 analysis project ready? 
Screenshot (497)
@SuryanshNaugraiya

**Comment by SuryanshNaugraiya** [comment]
@prathimacode-hub  yes the project COVID-19analysis using ML is ready

**Comment by SuryanshNaugraiya** [comment]
ok @prathimacode-hub i got your point about the project structure, but if i align my project in your's project structure, then i have to make changes in its frontend as well as in its backend part, becos all the things are connected and also it will not work properly, try to understand please.

**Comment by prathimacode-hub** [comment]
> ok @prathimacode-hub i got your point about the project structure, but if i align my project in your's project structure, then i have to make changes in its frontend as well as in its backend part, becos all the things are connected and also it will not work properly, try to understand please. The current project structure is in such a way that if someone will directly deploy it in some cloud platform it will start working. But if i changes its structure, then i have make a lot of changes in its frontend part, backend part and in its app.py file as well. And also if i changes its folder name from (static, template) to (images, frontend, backend) kit will not get deployed in heroku. I have tried this experiment with one of my project.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Ok, leave the static and templates. But other files should follow project structure. There is no proper project title to your folder. IPL you had kept as folder, it doesn't describe what the project is.
There should be "Dataset" and "Model". It's mere basic. @SuryanshNaugraiya

**Comment by SuryanshNaugraiya** [comment]
> Ok, leave the static and templates. But other files should follow project structure. There is no proper project title to your folder. IPL you had kept as folder, it doesn't describe what the project is.
> There should be "Dataset" and "Model". It's mere basic. @SuryanshNaugraiya

@prathimacode-hub now i have changed the project structure according to your wish, now please merge it.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
You had done a good project. Why did you hesitate to change? By the way, 'README.md' file is not in proper template. Project needs good elaboration that's when project is justified. The main reason I asked for changes is according to the format, one should start working only after issue is assigned. If this process is followed, you wouldn't have to do changes again as you would do it right the first time. Since this is already done project, you might felt hesitating to disturb the changes. If I accept it earlier, it would be unfair for others. That's the reason I stressed. Kindly do the needful changes and follow the README template given. You had done good analysis, you have to show it right. For sample, you can check this [README](https://github.com/prathimacode-hub/ML-ProjectKart/blob/main/GOT%20Episodes%20IMDb%20Rating%20Prediction/Model/README.md) file. @SuryanshNaugraiya

**Comment by SuryanshNaugraiya** [comment]
hey @prathimacode-hub i have updated the readme file, you can check it. And if you allow i can start working on the covid-19 analysis issue.

**Review by prathimacode-hub — APPROVED** [review]
Yayy, congrats on your first PR. Welcome to the repo officially. This was a fab and impressive project. Great start. Keep it up. 👏🎉👍@SuryanshNaugraiya

**Comment by SuryanshNaugraiya** [comment]
> Yayy, congrats on your first PR. Welcome to the repo officially. This was a fab and impressive project. Great start. Keep it up. 👏🎉👍@SuryanshNaugraiya

@prathimacode-hub thanks

**Pull request merged**
