### PR TITLE
Added Cotton Disease prediction

### PR DESCRIPTION
**Pull request by NEERAJAP2001**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #133 

### Describe the add-ons or changes you've made
Added New Project

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Output in the NoteBook

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Manasi2001** [comment]
Extremely impressive work @NEERAJAP2001. Well done!! ✨✨
Just make these minor changes, then it'll be perfect:
1. Rename the folder as 'Cotton Disease Prediction' and not 'Cotton-Disease-Prediction'.
2. Follow the README template and edit your README accordingly.
3. The requirements.txt file is added twice. Let go of one.

Once you do these, I'll merge it then. 🙃

**Comment by Manasi2001** [comment]
Still changes 2 and 3 are required @NEERAJAP2001. Also, put the final README in the Model folder itself.

**Comment by NEERAJAP2001** [comment]
Yeah okay @Manasi2001 !!

**Review by prathimacode-hub — APPROVED** [review]
Yayy. Welcome on your first PR in this repo officially. Congrats. That was an awesome work. Good job. Keep shining. 🎊🎉🙌 @NEERAJAP2001

**Pull request merged**
