### PR TITLE
Fish Weight Prediction

### PR DESCRIPTION
**Pull request by rammya29**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #162 

### Describe the add-ons or changes you've made

 I have added my model and dataset for fish weight prediction.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
    I have trained the model and it is tested in the google colab workspace

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Manasi2001** [comment]
Good job on the notebook @rammya29. However, there's no README. Add that according to the template. Also, rename your folder as 'Fish Weight Prediction' and not FishWeight Prediction. Do these changes, then I'll merge it :)

**Comment by rammya29** [comment]
How to change the name folder, mam?

**Comment by Manasi2001** [comment]
> How to change the name folder, mam?

Go to your forked copy of this project. Open your repo. Go to settings, from there you can easily change it. Also, rename the folder as Dataset and not 'DataSet'. This you can do by uploading the dataset again with corrected name. Just drag the updated folder and it will automatically get corrected.

**Comment by prathimacode-hub** [comment]
Why had you closed the PR? @rammya29

**Comment by rammya29** [comment]
I cannot able to do changes. So I made it new pull request

**Pull request closed without merging**
