### PR TITLE
Terrorist attack prediction

### PR DESCRIPTION
**Pull request by 23-24**
## Terrorist attack prediction

-I have created a model used to predict the upcoming attacks from the provided dataset.
analysis of the country ,region as well as month with higher rate of assassination attacktype and  visualization of these are also provided. Logistic regression, Decision Tree and Random forest classifier were used.

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

Closes:#255

### Describe the add-ons or changes you've made

Implemented the prediction models for terrorist attack prediction

## How Has This Been Tested?
I have run this project in my pc and it works fine

## Checklist:

- [x] My code follows the guidelines of this project.

- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure given. To know how it should look like. You can check through this [repo](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Appliances%20Energy%20Prediction). You will know the files you should add on and how to structure the project well. @23-24

**Comment by prathimacode-hub** [comment]
Yes, it's ok. You can add up a link to the dataset. You should never close issues or PR form your end. Why did you close? @23-24

**Comment by 23-24** [comment]
srry maam as I am new to opensource ,I thought that after correction we must again create a pull request

**Comment by prathimacode-hub** [comment]
> srry maam as I am new to opensource ,I thought that after correction we must again create a pull request

Do the changes to this concerned PR. No need to close.

**Comment by 23-24** [comment]
okk maam

**Comment by 23-24** [comment]
maam can you verify the changes made

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
- The README.md and Terrorist_attack_prediction.ipynb should be in "Model" folder
- Add up the accuracies of all the algorithms you had used in this project
- Provide a brief conclusion of the project and your name at the end of the file.
- Also the image link you had added is user-images content instead the image link should be the file path of the image present in this repository
- Add the images in "Images" folder.
Kindly do these changes. @23-24

**Comment by 23-24** [comment]
sure maam

**Comment by prathimacode-hub** [comment]
You havem't done the changes yet. @23-24

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
First of all, according to project structure the project title should be as " Terrorist Attack Prediction.
Also your .ipynb file needs more elaboration. You hadn't predicted accuracies of the algorithms you had used. 
"requirements.txt" file are missing few libraries.
For README.md file it's missing few things. Look through the README template given and be elaborative. Describe your project. Add accuracies predicted. Provide a comparison. Add up a detailed conclusion, add up the data visualizations image links and your name at the end of the file.
Add dataset in '"Dataset" folder.

Kindly do the needful changes. @23-24

**Comment by 23-24** [comment]
okk maam

**Comment by 23-24** [comment]
I am having my exams tomorrow. I wont delay it again ,will complete everything by tomorrow itself

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The project folder should be as "Terrrorist Attack Prediction"
Add an elaborate conclusion in "README.md" fole
The project file should be as "terrorist_attack_prediction.ipynb"
Add the dataset used in "Dataset" folder.
Also the README.md file should have the list of attributes given in the dataset. 

Kindly do these changes, @23-24

**Review by prathimacode-hub — APPROVED** [review]
Whoaa, this is amazing. Congrats on your first PR. Your PR is approved. Keep it up. Great start. ✨🎉👏@23-24

**Comment by 23-24** [comment]
Thankyou for your advices  Maam.I am really motivated to start my journey.

**Pull request merged**
