### PR TITLE
Heart Attack Analysis

### PR DESCRIPTION
**Pull request by harshita9621**
## Related Issue 

- To predict the chance of Heart attack.

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

Closes: #441 

### Describe the add-ons or changes you've made

- Importing Libraries
- Missing Value Analysis
- Categoric and Numeric Features
- Standardization
- Box - Swarm - Cat - Correlation Plot Analysis
- Outlier Detection
- Machine Learning Model

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by harshita9621** [comment]
@prathimacode-hub Review this PR.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Add "requirements.txt" file with all the libraries you had used in this project
In README.md, add a description of your project above and at the end elaborate the conclusion  derived out of it briefly along with your name at the end. 

Your notebook file looks fab. @harshita9621

**Comment by harshita9621** [comment]
@prathimacode-hub Make all the changes review this PR.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
I couldn't see the changes addressed for README. Kindly make sure it's pushed properly and changes are done. @harshita9621

**Comment by harshita9621** [comment]
@prathimacode-hub Please review their is changes which I make

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
I still couldn't see the changes addressed in your README.md file. I don't know what's going wrong from your end. Else do 1 thing, remove the README.md file from your forked repository. Create a new file, copy paste the information and address the changes mentioned. Then push it again to the PR. Hope this works. @harshita9621

**Comment by harshita9621** [comment]
@prathimacode-hub What changes you want in the readme

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
In README.md, add a description of your project above and at the end elaborate the conclusion derived out of it briefly along with your name at the end. @harshita9621

**Comment by harshita9621** [comment]
@prathimacode-hub I make the changes

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great going. Keep it up. 👏😎@harshita9621

**Comment by prathimacode-hub** [comment]
Kindly fill the PR provided in project channel for PR to get counted in DCP program. @harshita9621

**Comment by harshita9621** [comment]
@prathimacode-hub Kindly provide the form link

**Comment by prathimacode-hub** [comment]
Ok, let me share it here : https://docs.google.com/forms/d/e/1FAIpQLSc4vFamHEp_Inz45TZbo3R0nl3OOwrjZhX90aHSn_G8t0jPxA/viewform

Kindly fill it up.

**Pull request merged**
