### PR TITLE
Railway Track Fault Detection

### PR DESCRIPTION
**Pull request by Best-forever-003**
## Related Issue 

Railway Track Fault Detection

- Info about the related issue 

Analyses the defective railway tracks

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

Closes: #452 

### Describe the add-ons or changes you've made

I have trained the model using the concept of CNN

Give a clear description of what have you added or modifications made

The model figures out any defects in railway tracks and gives an alert. This works by classifying images.

## Type of change

Accidents can be avoided

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Best-forever-003** [comment]
@prathimacode-hub There is no CSV for this project madam as it works based on images. Thanks

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure given. It's not in right format. If you are using images as dataset add them in "Dataset" folder. @Best-forever-003

**Comment by Best-forever-003** [comment]
Madam @prathimacode-hub I tried uploading all images but it exceeds 25 MB henceforth I took a single screenshot and uploaded it

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Please follow the project structure given in README file of the project. @Best-forever-003

**Comment by Best-forever-003** [comment]
Updated Dataset Readme Madam @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The "requirements.txt" and "Railway_track_fault_detection.ipynb" should be in "Model" folder.
And README.md in "Railway Track Fault Detection" folder
The README.md is still not in right format and many things missing. Instead of writing things don't add up links, for example you had added "requirements.txt" link instead of writing the libraries imported by words.
Be elaborative enough and follow the template given. 

Do these changes. @Best-forever-003

**Comment by Best-forever-003** [comment]
image
Madam @prathimacode-hub You told me to follow this format according to this it's correct

**Comment by prathimacode-hub** [comment]
Yes, it's correct. But here it isn't showing up like that. @Best-forever-003

**Comment by Best-forever-003** [comment]
Madam @prathimacode-hub, the readme file in model folder is the attribute thing that you asked me to add up madam. Can you please check up madam

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
I'm saying about the format of the folder names and file names, those changes I asked couldn't be seen here.
The model folder should be titled as "Model"
Also add up the models you had used for this project and also their accuracy scores you had achieved. You can check with the [README](https://github.com/prathimacode-hub/ML-ProjectKart/blob/main/.github/readme_template.md) template here.

Kindly do these changes. @Best-forever-003

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
List out the models used along the accuracy as given in README template. @Best-forever-003

**Comment by Best-forever-003** [comment]
@prathimacode-hub Updated Madam

**Comment by Best-forever-003** [comment]
Updated Madam @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
Kudos to your efforts, your PR is approved. Impressive work and wonderful choice of the project. 🤩🙌 @Best-forever-003

**Comment by prathimacode-hub** [comment]
Kindly fill the form with your PR links. 2 PR's are merged from you. Your response hasn't turned up yet. Form is available in slack project channel. @Best-forever-003

**Comment by Best-forever-003** [comment]
@prathimacode-hub where madam

**Comment by prathimacode-hub** [comment]
In the form provided to add PR links. That's given in project channel. I shall add the form here for you.  Link : https://docs.google.com/forms/d/e/1FAIpQLSc4vFamHEp_Inz45TZbo3R0nl3OOwrjZhX90aHSn_G8t0jPxA/viewform

**Pull request merged**
