### PR TITLE
Driver drowsiness detection system

### PR DESCRIPTION
**Pull request by dilroseR**
### Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

Closes: #389 

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made
- Created a model which would alert the user whenever he/she drowses away!

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Describe how it has been tested
I've run it on my system & it has no issues

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

home_page1

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The project file should be as Driver_drowsiness_detection.ipynb"
You had done backend it would have been better if you had added a .pkl file as well into the project. 

Kindly do these changes. @dilroseR

**Comment by dilroseR** [comment]
> Changes to be done:
> The project file should be as Driver_drowsiness_detection.ipynb"
> You had done backend it would have been better if you had added a .pkl file as well into the project.
> 
> Kindly do these changes. @dilroseR

Can you check now. did both of them

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Outstanding work. This is fab representation and good choice of the project. Great going. 🙌🤩👌@dilroseR

**Comment by dilroseR** [comment]
> Your PR is approved. Outstanding work. This is fab representation and good choice of the project. Great going. 🙌🤩👌@dilroseR

Thankyou so much! @prathimacode-hub

**Pull request merged**
