### PR TITLE
Gun detection using YOLOv5

### PR DESCRIPTION
**Pull request by Pranay38**
## Related Issue 

- Info about the related issue 

- [x] KWOC 2023 Participant 
- [x] Contributor

Closes: #624 

#### Overview

- This pull request introduces an initial implementation of a gun detection project using YOLOv5, focusing on building a robust system to detect firearms within images. This project marks the inception of a dedicated solution for firearm detection.

 #### Project Features

**Gun Detection Model:**
Utilizes YOLOv5s architecture for object detection, specifically tailored for identifying guns within images.

**Training on Custom Dataset**:
Trains the model on a custom dataset containing firearm images to enable accurate detection.

**Functionalities Included:**
Incorporates functionalities for image processing, model training, and inference to detect guns within images.

**Purpose and Impact**

**Purpose:** This initial implementation aims to lay the groundwork for a reliable gun detection system, enhancing safety measures by automating firearm identification in images.

**Impact:** Provides a foundational structure for further development and improvement in firearm detection capabilities.
Changes Introduced

### New Project Initialization:

- Adds the initial set of files, including scripts, model configurations, and dataset placeholders.

## Type of change

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Model Training and Validation:
Trained and validated the gun detection model using a custom dataset to ensure accuracy and convergence.

### Manual Review:
Manually reviewed added files, scripts, configurations, and dataset placeholders for correctness and presence.

### Functional Validation:
Tested and confirmed operational functionalities for image processing, model training, and inference.

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Are you not a KWOC participant? @Pranay38

**Comment by Pranay38** [comment]
I have registered late but I have contacted the team , waiting for their response

**Comment by prathimacode-hub** [comment]
Kindly follow the guidelines and see the README to know the structure of the project. You can look into projects for reference to understand the outlook. Include the issue number in your PR. @Pranay38

**Comment by prathimacode-hub** [comment]
> I have registered late but I have contacted the team , waiting for their response

If you have any queries, don't hesitate to ask. You had done well but needs proper structure to be merged. @Pranay38

**Comment by Pranay38** [comment]
I will restructure it and send a new pull request tomorrow morning

**Comment by prathimacode-hub** [comment]
Instead of new pull request you can do the changes in current PR itself if you're comfortable. If you're creating new PR, then go ahead but don't delete this PR. And don't forget to add the issue number in your PR according to the format given. @Pranay38

**Comment by Pranay38** [comment]
Okay ma'am thank you . I'll do it ASAP.

**Comment by Pranay38** [comment]
@prathimacode-hub ma'am please check

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub ma'am please check

It's still not in structure. You complicated it. Let me know if you want a meet call for better clarity on structuring your PR? @Pranay38

**Comment by Pranay38** [comment]
> > @prathimacode-hub ma'am please check
> 
> It's still not in structure. You complicated it. Let me know if you want a meet call for better clarity on structuring your PR? @Pranay38

Ma'am would you please tell me what should be the template. I followed the dataset and model folder template which was provided here.

**Comment by Pranay38** [comment]
> > @prathimacode-hub ma'am please check
> 
> It's still not in structure. You complicated it. Let me know if you want a meet call for better clarity on structuring your PR? @Pranay38

Ma'am would you please tell me what should be the template. I followed the dataset and model folder template which was provided here.
Screenshot 2024-01-06 at 1 35 47 PM

**Comment by prathimacode-hub** [comment]
You can check the naming conventions to apply for the project structure, which will clear your query. I also could see unrelated files like .DS_Store, .ipynb checkpoints. 2 folders Gun Detection and Gun_Detection, rtf files etc. @Pranay38

**Comment by Pranay38** [comment]
> You can check the naming conventions to apply for the project structure, which will clear your query. I also could see unrelated files like .DS_Store, .ipynb checkpoints. 2 folders Gun Detection and Gun_Detection, rtf files etc. @Pranay38 

Ma'am the latest commit is the final commit

**Comment by Pranay38** [comment]
@prathimacode-hub I have made a new pull request #631

**Pull request closed without merging**
