### PR TITLE
Movies Recommendation System

### PR DESCRIPTION
**Pull request by Rutikab12**
## Related Issue : #128 

- Movie Recommendation System 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

### Describe the add-ons or changes you've made

This model will recommend movies with the help of the movies_metadata dataset from Kaggle.

## How Has This Been Tested?

Techniques Used

I have used two techniques to recommend movies

- Simple Recommendation System

It will recommend the top items based on a certain metric weighted score.

- Content-Based Movies Recommendation System

It will compute the cosine similarity scores for all movies based on the overview feature in our metadata dataset. 

With the help of TFIDF and cosine similarity, we get better recommendations.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

There are two empty README files. Remove the README.md file from "Model" folder
The main README.md file is not in the right template. You can find the template in this project. Follow it. Along with the description of the project you had provided.
The dataset information you added up in main "README.md" should be in "README.md" file that's in "Dataset" folder.
Add the libraries imported in your project in "requirements.txt" file. This should be in "Model" folder.

Kindly do the needful changes. @Rutikab12

**Comment by Rutikab12** [comment]
> Changes to be done:
> 
> There are two empty README files. Remove the README.md file from "Model" folder
> The main README.md file is not in the right template. You can find the template in this project. Follow it. Along with the description of the project you had provided.
> The dataset information you added up in main "README.md" should be in "README.md" file that's in "Dataset" folder.
> Add the libraries imported in your project in "requirements.txt" file. This should be in "Model" folder.
> 
> Kindly do the needful changes. @Rutikab12

Okay @prathimacode-hub . It will be done by tomorrow.

**Comment by Rutikab12** [comment]
Done with changes requested @prathimacode-hub . Have a look.

**Review by prathimacode-hub — APPROVED** [review]
Well done. Keep growing. Good work. Implementation looks cool. 👏👌 @Rutikab12

**Pull request merged**
