### PR TITLE
issue #18 Stock Price Prediction added

### PR DESCRIPTION
**Pull request by sy07**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #18 

### Describe the add-ons or changes you've made

- Data Exploration
- Model Creation(Moving Average,Linear Regression,k Nearest Neighbour,Prophet,LSTM)

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have tested the model on the given csv
## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [] My changes generate no new warnings.
- [ I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure given in README.md file of the project
Add project README.md and modify the changes according to the guidelines given.
It's not in right frame. @sy07

**Comment by sy07** [comment]
> Follow the project structure given in README.md file of the project
> Add project README.md and modify the changes according to the guidelines given.
> It's not in right frame. @sy07

Mam i want to make changes in the files. What should i do? Should i create new PR after changes?

**Comment by prathimacode-hub** [comment]
> > Follow the project structure given in README.md file of the project
> > Add project README.md and modify the changes according to the guidelines given.
> > It's not in right frame. @sy07
> 
> Mam i want to make changes in the files. What should i do? Should i create new PR after changes?

No, you can do the changes in your forked repository and push back the changes. No need of new PR. @sy07

**Review by prathimacode-hub — APPROVED** [review]
Well done. Your PR is approved. Keep rising up. Congrats. 🎉👏👍@sy07

**Pull request merged**
