### PR TITLE
Added Emotion Recognition based on NLP

### LINKED ISSUE #54: Emotion Recognizer in Python( NLP Based )
Hello!! I have an NLP-based Project Idea.
Problem staement : Emotion Recogiser 
I've been working on this already would be happy to add this project here.
Here is  a [glimpse](https://github.com/NEERAJAP2001/EmoRec) 
Please assign this issue to me so that I can start working.
Thanks

I'd Like to work on this as part of LGMSOC-21

I will work on front end + model + backend of the Project ( Fullstack )

### PR DESCRIPTION
**Pull request by NEERAJAP2001**
## Related Issue 

- Added Emotion Recognition based on NLP

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Fixes #54 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I've deployed it on Heroku , so manual testing has been done.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

The project files .py, .pkl, requirements. txt should be in "Model" folder
The images and screenshots should be in "Images" folder

Kindly do the needful changes. Other than this, all perfect. @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Yeah, Changes done!! Review @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
- Kindly elaborate the README file of your project. Add the purpose of the project, what it does, what's the use, steps to be followed, how it works or compiles and the conclusion.
- Also emotion_reco.py, place it in "Model" folder.

Kindly do the changes @NEERAJAP2001

**Comment by TanweerulHaque** [comment]
@NEERAJAP2001 Your PR is amazing. It is merged now.

**Comment by NEERAJAP2001** [comment]
Thanks @TanweerulHaque

**Pull request merged**
