### PR TITLE
Pycaret file contribution for Hacktoberfest

### PR DESCRIPTION
**Pull request by DhruvBajaj01**
## Related Issue 

- Info about the related issue 

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
What's the issue title? Also there are separate templates to follow. You can work only after an issue is assigned to you. I'm not clear about the issue title? Can you let me know about it? @DhruvBajaj01

**Comment by DhruvBajaj01** [comment]
Oh sorry I though, I can directly add my old project

**Comment by DhruvBajaj01** [comment]
Like I didn't go through any issue as such.

**Comment by prathimacode-hub** [comment]
No worries. Once go through the contributing guidelines and open issues. @DhruvBajaj01

**Pull request closed without merging**
