### PR TITLE
Uber Fare predictions 

### PR DESCRIPTION
**Pull request by Soumayan-pal01**
## Uber fare prediction

- The main objective of project is to design an algorithm which will tell the fare to be charged for a passenger. Multiple machine learning algorithms have been used to develop a regression model. 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #37

### Describe the add-ons or changes you've made

Trained a new model using multiple regression algorithms and used the best one to predict the fare in the test set.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — APPROVED** [review]
The finest explanation and perfect approach. Your work is spell bounding. Your PR is approved. No words. Can't wait to see, what you take up as a next issue. 👌👌👌 @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
> The finest explanation and perfect approach. Your work is spell bounding. Your PR is approved. No words. Can't wait to see, what you take up as a next issue. 👌👌👌 @Soumayan-pal01

Thank you so much @prathimacode-hub

**Comment by Soumayan-pal01** [comment]
I had a question @prathimacode-hub actually. I have worked on a image compression project where the K-Means clustering algorithm has been used to reduce the quality of the images by converging the pixel count into k-clusters. Can I create a new issue for that project?

**Comment by prathimacode-hub** [comment]
Sure, you can. This is an inclusive repository as long as you use ML algorithms or related to ML. That's all welcomed. Seems to be an interesting project coming from you. Go ahead to raise an issue. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
> Sure, you can. This is an inclusive repository as long as you use ML algorithms or related to ML. That's all welcomed. Seems to be an interesting project coming from you. Go ahead to raise an issue. @Soumayan-pal01

Okay. Thank you.

**Pull request merged**
