### PR TITLE
 News Articles Classification 

### LINKED ISSUE #501: News Articles Classification
Define You:

- [√] HacktoberFest Participant
- [ ] Contributor

This model will classify any text into different groups of news like politics, religion, sports, space etc.

### PR DESCRIPTION
**Pull request by KhushiChaudhary744**
fix #501 

Related Issue

   News Articles Classification

[x] Hacktoberfest2021 Participant

Type of change

fixes: #582 
What sort of change have you made:

[ ] Bug fix (non-breaking change which fixes an issue)
[x] New feature (non-breaking change which adds functionality)
[ ] Code style update (formatting, local variables)
[ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

    This change requires a documentation update

Checklist:

[x] My code follows the guidelines of this project.
[x] I have performed a self-review of my own code.
[x] I have commented my code, particularly wherever it was hard to understand.
[x] I have made corresponding changes to the documentation.
[x] My changes generate no new warnings.
[x] I have added things that prove my fix is effective or that my feature works.
[x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The project file should be in snake case : news_article_classification.ipynb. Use multiple algorithms and compare the accuracy. 1 is not sufficient. Along with it, in start add short intro and overall summary at the end
Readme file should be as README.md and elaborate your README file, there is a README template to follow and also the data visualizations, accuracies attained and conclusion.
Add PR template to your PR along with issue number. 
Add "requirements.txt" file with all the libraries included in you project

Kindly work on it. @KhushiChaudhary744

**Comment by KhushiChaudhary744** [comment]
Okay!

**Comment by KhushiChaudhary744** [comment]
@prathimacode-hub please review the changes.

**Comment by prathimacode-hub** [comment]
By when are you expected to do? Fest is about to end? @KhushiChaudhary744

**Review by prathimacode-hub — APPROVED** [review]
README can be elaborated briefer. But I don't want your efforts to go wasted as you haven't replied. You have done a good work. PR approved. ✔👏👌@KhushiChaudhary744

**Pull request merged**
