### PR TITLE
Rain Prediction

### PR DESCRIPTION
**Pull request by Isha307**
## Related Issue 

- RainTomorrow is the target variable to predict on the basis of some given Features.

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: [#158](https://github.com/prathimacode-hub/ML-ProjectKart/issues/158)

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Locally

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Manasi2001** [comment]
Nicely done @Isha307! The README needs a little bit of tweaking though. Refer to this [template](https://github.com/prathimacode-hub/ML-ProjectKart/blob/main/.github/readme_template.md) and make the changes.

**Review by prathimacode-hub — APPROVED** [review]
Good work. Whooa, your PR is approved. Great start. Wonderful way of representing each feature. Kindly do the changes, @Manasi2001 has asked for. Then it will be merged. 👌🎉✨@Isha307

**Comment by Isha307** [comment]
> Good work. Whooa, your PR is approved. Great start. Wonderful way of representing each feature. Kindly do the changes, @Manasi2001 has asked for. Then it will be merged. 👌🎉✨@Isha307

okay

**Comment by Manasi2001** [comment]
Perfect @Isha307. Really good job!!
Merging...

**Pull request merged**
