### PR TITLE
Added another DL Project

### PR DESCRIPTION
**Pull request by iamarecklessdev**
## Related Issue 

- Info about the related issue 

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made

Added a Sentiment Classifier using DNN

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Changes are verified by me and waiting for pull request to be merged.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Whats your issue number? @iamarecklessdev

**Comment by iamarecklessdev** [comment]
I commented the same regarding the issue number in Contribute to this repo 🔔 #4.

**Comment by iamarecklessdev** [comment]
#578 opened yesterday by iamarecklessdev
May be this is the one you are asking for @prathimacode-hub

**Comment by prathimacode-hub** [comment]
> #578 opened yesterday by iamarecklessdev May be this is the one you are asking for @prathimacode-hub

Yes, but this should be included in your PR template. @iamarecklessdev

**Comment by prathimacode-hub** [comment]
Changes to be done:

The project file should be in snake case : womens_shopping_sentiment_analysis.ipynb. Use multiple algorithms and compare the accuracy. 1 is not sufficient. Along with it, in start add short intro and overall summary at the end
Be more briefer and also along with it add the data visualizations, accuracies attained and conclusion.
Add issue number to your PR template.
Add "requirements.txt" file with all the libraries included in you project
Remove the .DS_Store file 

Kindly work on it. @iamarecklessdev

**Comment by prathimacode-hub** [comment]
Why have you closed? @iamarecklessdev

**Pull request closed without merging**
