### PR TITLE
Youtube Video Recommendation System

### PR DESCRIPTION
**Pull request by Akash20x**
## Related Issue 

- Youtube Video Recommendation System

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #246 

### Describe the add-ons or changes you've made

This model will recommend the video titles on proving the search query by user.
Applied two models: KNN and Tf-idf Vectorizer for recommending videos.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It is tested on google colab.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by Akash20x** [comment]
@prathimacode-hub Please check my pull request

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub Please check my pull request

Will check on it tomorrow. @Akash20x

**Comment by Akash20x** [comment]
> > @prathimacode-hub Please check my pull request
> 
> Will check on it tomorrow. @Akash20x

OK

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Oh my goodness, your first PR. You had built it from the very scratch. Though you had used 2 models for recommendations, whatever you had done, you had nailed it. The clear explanation and elaboration is totally fab. 

Can't get anything better than this, I feel you can add up an another model as well with it to see the efficiency. Like you did elaborate your project, you can also elaborate the conclusion more briefly in your README.md file.

**Comment by Akash20x** [comment]
> Oh my goodness, your first PR. You had built it from the very scratch. Though you had used 2 models for recommendations, whatever you had done, you had nailed it. The clear explanation and elaboration is totally fab.
> 
> Can't get anything better than this, I feel you can add up an another model as well with it to see the efficiency. Like you did elaborate your project, you can also elaborate the conclusion more briefly in your README.md file. @Akash20x

OK, I will try to do it

**Comment by Akash20x** [comment]
> Oh my goodness, your first PR. You had built it from the very scratch. Though you had used 2 models for recommendations, whatever you had done, you had nailed it. The clear explanation and elaboration is totally fab.
> 
> Can't get anything better than this, I feel you can add up an another model as well with it to see the efficiency. Like you did elaborate your project, you can also elaborate the conclusion more briefly in your README.md file. @Akash20x

OK i will do it.

**Comment by Akash20x** [comment]
> Oh my goodness, your first PR. You had built it from the very scratch. Though you had used 2 models for recommendations, whatever you had done, you had nailed it. The clear explanation and elaboration is totally fab.
> 
> Can't get anything better than this, I feel you can add up an another model as well with it to see the efficiency. Like you did elaborate your project, you can also elaborate the conclusion more briefly in your README.md file. @Akash20x

@prathimacode-hub
I can't add another model because its too difficult for me as I have less knowledge in these recommendation systems so it will take too much time and I can't spend all time for 1 issue.

**Comment by Akash20x** [comment]
> Oh my goodness, your first PR. You had built it from the very scratch. Though you had used 2 models for recommendations, whatever you had done, you had nailed it. The clear explanation and elaboration is totally fab.
> 
> Can't get anything better than this, I feel you can add up an another model as well with it to see the efficiency. Like you did elaborate your project, you can also elaborate the conclusion more briefly in your README.md file. @Akash20x

@prathimacode-hub
I didn't know how to find efficiency in these recommendation systems models and so can't add another model as I have less knowledge in these recommendation systems.

**Comment by prathimacode-hub** [comment]
> > Oh my goodness, your first PR. You had built it from the very scratch. Though you had used 2 models for recommendations, whatever you had done, you had nailed it. The clear explanation and elaboration is totally fab.
> > Can't get anything better than this, I feel you can add up an another model as well with it to see the efficiency. Like you did elaborate your project, you can also elaborate the conclusion more briefly in your README.md file.
> 
> @prathimacode-hub
> I didn't know how to find efficiency in these recommendation systems models. I searched it on the Internet but didn't understand how to apply it in recommendation systems models so i can't add another model as I have less knowledge in these recommendation systems.

Ok, that's upto you. Your PR is approved. 👏🎉✨@Akash20x

**Pull request merged**
