### PR TITLE
News Classification

### PR DESCRIPTION
**Pull request by drishtibaranwal**
## Related Issue 

- Info about the related issue 

- [✅] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #501 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✔ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [✔ ] My code follows the guidelines of this project.
- [✔  ] I have performed a self-review of my own code.
- [✔  ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [✔  ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly follow the project structure given. @drishtibaranwal

**Comment by drishtibaranwal** [comment]
Ma'am can you tell me the mistakes in project structure

**Comment by prathimacode-hub** [comment]
There are many files missing in your project. And you can check with the project structure in README file of the project. Once you push all the relevant files. Then I shall address all the changes at once. @drishtibaranwal

**Comment by drishtibaranwal** [comment]
Maam I am not able add more files. Please tell me from where I can add more files

**Comment by prathimacode-hub** [comment]
> Maam I am not able add more files. Please tell me from where I can add more files

Add the files in your forked repository and repush it again. @drishtibaranwal

**Comment by drishtibaranwal** [comment]
see Ma'am and tell please from where I can create new file

**Comment by prathimacode-hub** [comment]
> see Ma'am and tell please from where I can create new file

You shouldn't add like this, instead upload them in your forked repository in your project folder. You can do it directly using upload files and push it back again. It would automatically save up the changes. @drishtibaranwal

**Comment by prathimacode-hub** [comment]
Its been 4 days and no update from you yet. @drishtibaranwal

**Comment by prathimacode-hub** [comment]
Are you willing to do up the changes or not? Last date to merge PR's is tomorrow. Else I have no option that to remove the label. @drishtibaranwal

**Comment by prathimacode-hub** [comment]
No response and time is up for contributions. So label is removed. You can do the changes and submit the work. But won't be counted under LGMSOC program. But still holding PR for this long is not right. I shall wait for 2 more days before I closing this PR. If you want this contribution to be valuable, then kindly complete the PR in given time. @drishtibaranwal

**Pull request closed without merging**
