### PR TITLE
Covid19Tracker

### PR DESCRIPTION
**Pull request by mv1249**
This is an Analytical Model which keeps track of Covid-19 in India all the active cases,state wise analysis,the vaccination analysis across various states and union territories and many more

## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Have you got the issue assigned to you? What's the issue number? @mv1249

**Comment by mv1249** [comment]
Here is the preview

https://github.com/mv1249/Covid19Tracker/issues/1#issue-919445508

**Comment by prathimacode-hub** [comment]
What did i ask? Have you got assigned to this issue? @mv1249

**Comment by mv1249** [comment]
> What did i ask? Have you got assigned to this issue? @mv1249

No

**Comment by prathimacode-hub** [comment]
> > What did i ask? Have you got assigned to this issue? @mv1249
> 
> No

Then what's the purpose of the pull request, it's invalid PR.

**Comment by prathimacode-hub** [comment]
You can come up with unique issue which isn't available in the repo. And also follow the procedure given. @mv1249

**Pull request closed without merging**
