### PR TITLE
Added Heart disease prediction model

### PR DESCRIPTION
**Pull request by raunak51299**
## Heart disease prediction

- I made a model to predict heart disease using SVM and K-Nearest Neighbours techniques  and then compared their accuracies.

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #58

### Describe the add-ons or changes you've made

- I have added a heart disease dataset from [kaggle](https://www.kaggle.com/ronitf/heart-disease-uci)
- Then I made a ipynb file which contains SVM and K-Nearest Neighbors model from sklearn .

## Type of change

- [x] My code follows the code style of this project.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — COMMENTED** [review]
Hey, this issue is not considered as it was raised before the time. Do raise a new issue, stating project title as heart disease prediction first. I shall assign you the issue then. After that, you are allowed to raise a PR. And one more thing, I had noticed is you had used SVM model. How is the performance and what's the accuracy you are getting? It's better if you compare with atleast 2-3 alogrithms to analyze the right performance. Also there is README template to follow. Just add up the details in template to your README file. As well, the PR is not in right project structure. Check the README file of the project. .csv file should be in Dataset folder and .ipynb, README and requirements.txt file would be in Model folder. 

Get the issue assigned to you first, and then raise your PR again with necessary changes I had mentioned. All the best. @raunak51299

**Comment by raunak51299** [comment]
ok will do

**Comment by raunak51299** [comment]
Should I close this pull request?

**Comment by prathimacode-hub** [comment]
If you close the PR, your efforts will go wasted. Never close anything from your end. @raunak51299

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
- Using atleast 2-3 algorithms doesn't mean doing it seperately. But use it in a single .ipynb file and comparing the accuracies simultaneously. 
- The folder name should be "Model" not "Models"
-file_name should be strictly snake case.
(It does mean that file name should be as heart_disease_prediction.ipynb)

Kindly do these changes. You can do it.  ✔

**Comment by raunak51299** [comment]
## Heart disease Prediction

- I made models to predict heart disease using SVM and K-Nearest Neighbours techniques

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #58 and #9

### Describe the add-ons or changes you've made

- I have added a heart disease dataset file from [kaggle](https://www.kaggle.com/ronitf/heart-disease-uci).
- Then I have created two models (i.e SVM and K-nearest Neighbors) and trained them over the dataset.
## Type of change

What sort of change have you made:

- [x] My code follows the code style of this project.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

**Comment by raunak51299** [comment]
> * Using atleast 2-3 algorithms doesn't mean doing it seperately. But use it in a single .ipynb file and comparing the accuracies simultaneously.
> * The folder name should be "Model" not "Models"
>   -file_name should be strictly snake case.
>   (It does mean that file name should be as heart_disease_prediction.ipynb)
> 
> Kindly do these changes. You can do it. ✔

ok sure

**Comment by prathimacode-hub** [comment]
Good to see you make changes. Can you change the PR title and commit message, as you had compared it using 2 algorithms. @raunak51299

**Comment by prathimacode-hub** [comment]
Thanks for rectifying the changes. Official labels would come out at noon. So you are good to take up a new issue to work on. I shall merge this PR, when official labels are tagged to this PR. Remove #9 label as it is not in consideration. Only #58 marks up your issue. @raunak51299

**Comment by raunak51299** [comment]
> Thanks for rectifying the changes. Official labels would come out at noon. So you are good to take up a new issue to work on. I shall merge this PR, when official labels are tagged to this PR. Remove #9 label as it is not in consideration. Only #58 marks up your issue. @raunak51299

Thank you

**Comment by prathimacode-hub** [comment]
Your PR is merged successfully.  Congratulations.🎇@raunak51299

**Pull request merged**
