### PR TITLE
Dog breed identification

### PR DESCRIPTION
**Pull request by Anshal55**
## Related Issue 

- Model and Deployment of dog breed detection based on images 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

### Describe the add-ons or changes you've made

Functional model and prediction using images.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have tested it on multiple images under various scenarios.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Anshal55** [comment]
Sorry for the last one !!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
That's Ok. It happens. You're allowed to make mistakes.

Changes to be done

- Add issue number in your PR commit message
- The readme file should be titled as "README.md" file
- README file needs good elaboration of the project. Add the steps to be followed.
- Add README.md file in "Model" folder.
- The project repository should be titled as "Dog Breed Identification"
- The file names should be in snake case. So the project file name would be as dog_breed_identification.ipynb.

Kindly do the needful changes. @Anshal55

**Comment by prathimacode-hub** [comment]
> Sorry for the last one !!

No worries, this is how you learn and grow.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done

Merge both the README's together and place that README.md in "Model" folder
Project folder name should be titled as "Dog Breed Identification"

Do these changes. @Anshal55

**Comment by Anshal55** [comment]
Okay doing.
Thanks!! @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Change the project folder name to "Dog Breed Identification". And you will done. @Anshal55

**Comment by Anshal55** [comment]
> Change the project folder name to "Dog Breed Identification". And you will done. @Anshal55

How can I do that I can't seem to figure out.

**Comment by Anshal55** [comment]
Is is okay now @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
Yes, it's perfectly good. Just noticed your msg. Good to see your learning journey. You had done a wonderful work. Your PR is approved. You can take up an another issue to work on. This PR will be merged soon. @Anshal55

**Comment by Anshal55** [comment]
> Yes, it's perfectly good. Just noticed your msg. Good to see your learning journey. You had done a wonderful work. Your PR is approved. You can take up an another issue to work on. This PR will be merged soon. @Anshal55

Thanks I will put a request for that.

**Pull request merged**
