### PR TITLE
Wine Quality Prediction

### PR DESCRIPTION
**Pull request by Rutikab12**
## Related Issue : #79 

- Wine Quality Prediction 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes : #79 

### Describe the add-ons or changes you've made

I have created a model which will predict the quality of wine with a certain set of features.

## How Has This Been Tested?

Tested with algorithms such as
1. Support Vector Classifier  ---> Accuracy : 86%
2. Random Forest Classifier  ---->Accuracy: 88%

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by prathimacode-hub — COMMENTED** [review]
I could see you had done backend and front end as well along with model creation? @Rutikab12

**Comment by Rutikab12** [comment]
> I could see you had done backend and front end as well along with model creation? @Rutikab12

yes @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
That's great to know. You had done a fab work. Very well showcased. This PR is approved. 🏷🎇You can take up an another issue to work on. Kudos to you. @Rutikab12

**Comment by Rutikab12** [comment]
> That's great to know. You had done a fab work. Very well showcased. This PR is approved. 🏷🎇You can take up an another issue to work on. Kudos to you. @Rutikab12

Thank You @prathimacode-hub

**Pull request merged**
