### PR TITLE
KWOC 2023 : Body Parts Recognition

### LINKED ISSUE #628: KWOC 2023 : Body Parts Classification
Define You:

- [x] KWOC 2023 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
- Identifying the images of different body parts using ml model.

**Describe the solution you'd like...**
- Analysing the dataset.
- EDA processing.
- Filtering the dataset so that which can easily fit into any type of the dataset.
- Applying the different type of the algorithms.
- Summarizing all the algorithms at the end of the notebook.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## Related Issue 

closes #628 

- Info about the related issue 

- [x] KWOC 2023 Participant 
- [x] Contributor

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made
- Building a recognition model to recongnize body parts.
- Accuracy achieved - 99.24%

## Type of change

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Adding the dataset link just install the `requirements.txt` dependencies and start the model.
- Second method, i have made this model on google colab so just upload the file and link your `kaggle.json` file and run all the cells with GPU.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@prathimacode-hub please review this code and requested to merge this project under KWOC'23

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
That's a good choice of project. Keep contributing.

**Things to Add :**
Keep your project repository title as "Body Parts Classification". 
Looking at notebook file, you can apply multiple algorithms / techniques to bring the score comparison and choose out to right fit model for the solution accordingly.
In README.md file, under Conclusion topic : illustrate the data analysis insights you had understood from this classification and one liner conclusion of the results along with accuracy score. 
@Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@prathimacode-hub please again review this pr and requested to merge it under KWOC'23

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and have to admit your right choice of project. Kudos on taking this initiative. Well done. Keep contributing. ✔👌 @Avdhesh-Varshney

**Pull request merged**
