### PR TITLE
Amazon Mobile Phones reviews sentiment Analysis

### PR DESCRIPTION
**Pull request by drashtipatel2503**
issue  #311

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add a proper PR template along with issue number. Also PR title doesn't tell what your project was. It's generic be specific. @drashtipatel2503

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project strurcture given in README file of the project. Needs more files as well. @drashtipatel2503

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
It's still not in project structure. Kindly correct it. @drashtipatel2503

**Comment by drashtipatel2503** [comment]
Amazon Mobile Phones Reviews Sentiment Analysis

I am LGM-SOC'21 participant

closes  #311

Added New feature

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ]  I have made corresponding changes to the documentation.
- [ ]  My changes generate no new warnings.

**Comment by prathimacode-hub** [comment]
Where are the details described in the PR template? @

**Comment by Manasi2001** [comment]
@drashtipatel2503 just 2 changes:
1. Rename the Readme as 'README'.
2. Rename cell phone reviews.ipynb as cell_phone_reviews_analysis.ipynb

Rest seems okay. Good job on the notebook :)

**Comment by prathimacode-hub** [comment]
Kindly add the PR template along with the issue number and project details. @drashtipatel2503

**Comment by drashtipatel2503** [comment]
edited the pr template above and added different models for comparison, added same to readme.md file and renamed files.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly add name at the end of the README.md file and also since it's analysis it would have been better if you have illustrated it using data visualizations before training the model. So let me know if you want to work more or shall I merge once you add up a name at the end of the README.md file. @drashtipatel2503

**Comment by drashtipatel2503** [comment]
I have added the name in readme file. Please merge this PR.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Congrats and welcome to repo officially. This was a great start. Well done. 🎉✨👏@drashtipatel2503

**Pull request merged**
