### PR TITLE
Car Price Prediction

### PR DESCRIPTION
**Pull request by vijay3150**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [/ ] DevIncept Participant
- [ /] Contributor

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
PR template has no details embedded. Check up with appropriate boxes and add up the issue number in PR template. Provide information about things you had done in PR. Template is just copy pasted and nothing updated. Once you do that, I shall check on with the PR. @vijay3150

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
No proper project structure. No proper README file. @vijay3150

**Comment by prathimacode-hub** [comment]
Its still not in proper structure and also no details in your PR template. @vijay3150

**Comment by prathimacode-hub** [comment]
Why did you close the PR? You should never close PR or issues from your end. @vijay3150

**Comment by vijay3150** [comment]
Thats my mistake I think i want to create new PR and do the changes thats why i closed PR but now my laptop has issues and files were not in that so I wish to un assign from this project mam so closed my PR and I commented in Issue section mam

**Comment by prathimacode-hub** [comment]
That's ok. I had already unassigned you. @vijay3150

**Pull request closed without merging**
