### PR TITLE
Added Gender Classification Project

### PR DESCRIPTION
**Pull request by NEERAJAP2001**
## Related Issue 

Added Gender Classification Project

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #305 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Manasi2001** [comment]
Good work @NEERAJAP2001, but some changes are required:
1. Remove this file. It's already been added in the Images folder.
image
2. Check the README template given here and make changes in readme accordingly.
image

Rest seems okay.

**Comment by NEERAJAP2001** [comment]
> 3\. You haven't added the Dataset folder. It needs to be there.

@Manasi2001 The dataset is too big , so I've given the link.
Thanks

**Comment by Manasi2001** [comment]
> > 3. You haven't added the Dataset folder. It needs to be there.
> 
> @Manasi2001 The dataset is too big , so I've given the link.
> Thanks

Okay, no problem then @NEERAJAP2001. Although your README (in Model's folder) is descriptive enough but try to follow the given template. Anyways, it's good to go from my side, I'm going to wait for the PA to take a look as well. You did really good. 😊 Keep it up!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add a description about the project in 'README.md' file. Other than that, it's acceptable for this project. 👍😎@NEERAJAP2001

**Review by prathimacode-hub — APPROVED** [review]
For now I'm accepting it, but it still lacks proper template. Kindly make sure to follow the template given next time. This doesn't reduce your work. You had done an impressive job. Very well done. 🤩🏷🙌@NEERAJAP2001

**Pull request merged**
