### PR TITLE
Anime Recommendation System

### PR DESCRIPTION
**Pull request by photon149**
## Related Issue 

- Info about the related issue 

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #596 issue number that will be closed through this PR

### Describe the add-ons or changes you've made

we implemented a recommendation system to suggest best anime , based on user input.A function or model to recommend anime based on the respective anime we have inputted.For this we have created a function , which works in a manner , that it looks at correlation between various anime series , based on factors like rating,genre etc.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually run and tested 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by photon149** [comment]
@prathimacode-hub please check and review the same.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README needs elaboration. @photon149

**Comment by photon149** [comment]
Made the changes ,  please check the same.
@prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add description, models used and data visualization images as it's a recommendation systems. @photon149

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good to see your pace.✨🙌@photon149

**Pull request merged**
