### PR TITLE
Flight Fare Prediction

### PR DESCRIPTION
**Pull request by Soumayan-pal01**
## Flight Fare Prediction

- The aim of the project is to predict the fare of different Airlines covering different routes

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #210

### Describe the add-ons or changes you've made

In this project we have performed a detailed analysis and visualization of the training dataset with different Exploratory Data Analysis techniques. Then a comaprative analysis of different Regressons have been done to predict the flight fare predictions.After performing the model comparative analysis we can conclude that the hypertuned Random Forest regressor model performs best with an accuracy of 84%
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Small changes:

In README.md file, add all the accuracies and show the comparison. 
I guess this project is missing. .pkl file. If it's there do add it in "Model" folder.  @Soumayan-pal01

**Review by prathimacode-hub — APPROVED** [review]
As usual, fab and impressive. You had nailed it. Amazing work. Whooaa. 🙌🤩@Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
> Small changes:
> 
> In README.md file, add all the accuracies and show the comparison.
> I guess this project is missing. .pkl file. If it's there do add it in "Model" folder. @Soumayan-pal01

I have added the model comparison in the README.md file. The .pkl model file was exceeding 100 MB so I have archived it in .rar format file.

**Comment by Soumayan-pal01** [comment]
> As usual, fab and impressive. You had nailed it. Amazing work. Whooaa. 🙌🤩@Soumayan-pal01

Thanks @prathimacode-hub

**Pull request merged**
