### PR TITLE
Web page phishing detection 

### PR DESCRIPTION
**Pull request by kadatatlukishore**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

Closes: #428 

### Describe the add-ons or changes you've made

- Added **Web Page Phishing Detection** project.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
Dataset: [**Here**](https://www.kaggle.com/manishkc06/web-page-phishing-detection)

### CODE REVIEW

**Comment by kadatatlukishore** [comment]
Hello @prathimacode-hub Can you please confirm if any changes required?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
You had used 4 models, add up those accuracies and provide a brief conclusion and your name at the end of the file in README.md
Your README needs more details. @kadatatlukishore

**Comment by kadatatlukishore** [comment]
> You had used 4 models, add up those accuracies and provide a brief conclusion and your name at the end of the file in README.md
> Your README needs more details. @kadatatlukishore

Thanks for your inputs @prathimacode-hub . Will make necessary changes.

**Comment by kadatatlukishore** [comment]
@prathimacode-hub I've made required changes as per input on this. Please confirm. Thanks !

**Review by prathimacode-hub — APPROVED** [review]
Wow, amazing visualizations. Wonderfully executed. Clear analysis. Very well described. It's a level 4 work. Keep it up. Congrats. Your PR is merged. 🤩🎉@kadatatlukishore

**Comment by prathimacode-hub** [comment]
Also kindly send me your full name and your email id. 👍@kadatatlukishore

**Comment by kadatatlukishore** [comment]
Thank you so much @prathimacode-hub, means a lot !
Fullname: Kadatatlu Kishore
Email: vskishore408@gmail.com

**Pull request merged**
