### PR TITLE
Cervical Cancer Risk Prediction

### PR DESCRIPTION
**Pull request by abhisheks008**
## Related Issue #326 
# Cervical Cancer Risk Prediction

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

Closes: #326

### Describe the add-ons or changes you've made
The goal of this project is to create a prediction model which will predict the cervical cancer risk for a patient so that doctors can take the precautionary things as fast as possible.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
The models are being tested based on the accuracy scores. [AUROC]
## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — APPROVED** [review]
The way you choose projects and challenge yourself by giving your best into the projects makes me feel astonished. Never seen anyone be so consistent in delivering it perfectly. 🎊🤩@abhisheks008

**Comment by abhisheks008** [comment]
Thank you ma'am for motivating me every time to take up new challenges, and I'm pushing myself hard to get the perfect outcome!

**Comment by prathimacode-hub** [comment]
> Thank you ma'am for motivating me every time to take up new challenges, and I'm pushing myself hard to get the perfect outcome!

Most welcome. I understand it, but enjoy these challenges, don't feel it as pressure. And as you know, you had set your bar very high. So we kind of expect more from you yet you never miss to reach the bar you had set. @abhisheks008

**Comment by abhisheks008** [comment]
Yeah sure ma'am! Again thanks a lot for the motivation!

**Pull request merged**
