### PR TITLE
Solar Eclipse Classification

### PR DESCRIPTION
**Pull request by Soumayan-pal01**
## Solar Eclipse Classification

- The aim of this project is to classify among the main types of Solar eclipses, which are : P = Partial Eclipse, A = Annular Eclipse, T = Total Eclipse, H = Hybrid or Annular/Total Eclipse. Multiple classifier algorithms have been compared to perform predictions. 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #142

### Describe the add-ons or changes you've made

Trained a new model using multiple classification algorithms and used the best one to predict the type of solar eclipse

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Manasi2001** [comment]
You can let go of checkpoints file @Soumayan-pal01. Rest seems perfect. Impressive work!!

**Review by prathimacode-hub — APPROVED** [review]
As usual, what can I say. Excellent work. That's an awesome selection of project. Crystal clear. Wods fall short. 👌🙌@Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
> As usual, what can I say. Excellent work. That's an awesome selection of project. Crystal clear. Wods fall short. Kindly do the changes, @Manasi2001 mentioned.👌🙌@Soumayan-pal01

Thank you so much @prathimacode-hub

**Comment by Soumayan-pal01** [comment]
> You can let go of checkpoints file @Soumayan-pal01. Rest seems perfect. Impressive work!!

I have done the required changes. Please check @Manasi2001

**Comment by Manasi2001** [comment]
Very well done! Merging...

**Pull request merged**
