### PR TITLE
Added Organ Donors Prediction

### PR DESCRIPTION
**Pull request by akash435**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #429

### Describe the add-ons or changes you've made
Added Organ Donors Prediction.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (Only for Front End and UI/UX Designers)

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
PR approved. Great going. There is much more to play with in this prediction. It's just like point to point. If you want to work or should I merge it? @akash435

**Comment by akash435** [comment]
Then, I would prefer to work more on it, please don't merge it now

**Comment by akash435** [comment]
@prathimacode-hub  updated the model with below changes, please check it.
visualized the data with countplot and added XG Boost algorithm

**Review by prathimacode-hub — APPROVED** [review]
Outstanding work, this is how a project should look like. Loved your initiation to make it better. 🙌🤩@akash435

**Pull request merged**
